### ISSUE TITLE
Add APHL Learning Center URL to documentation

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#1044]
I keep losing this, but Jackie re-sent me the URL for the APHL-assisted docker training : https://learn.aphl.org/learn/course/external/view/elearning/355/intermediate-docker-bioinformatics-workshop

We should put this... somewhere.

**Comment by kapsakcj** [comment]
perhaps add this into PR #903 ? I added a section for Training to the main README.md there

**Comment by erinyoung** [comment]
That sounds like a great idea!
