### ISSUE TITLE
[Container Request]: integron_finder

### ISSUE THREAD

**Issue by kprus** [StaPH-B/docker-builds#1071]
### What tool are you looking for and why?

I use [Integron_Finder](https://github.com/gem-pasteur/Integron_Finder) often for comparing and annotating long-read genome assemblies and would love to have a StaPH-B container for it to match all the other containers in my nextflow pipeline :-)

**Comment by Kincekara** [comment]
Thank you for suggesting the integron_finder! It will be added to the StaPH-B docker images.
