### ISSUE TITLE
Unable to open the fasta file

### ISSUE THREAD

**Issue by AnoshMostaghimi** [StaPH-B/docker-builds#1101]
I am unable to run the test-genome-A1.fasta and would appreciate any help in letting me know what I am doing wrong. 

As a first step, I verify that I have a working container by executing and seeing the following:
$ docker run staphb/genoflu genoflu.py -v
genoflu.py: version 1.03

I then attach a volume to the container and everything works as expected
$ docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data1 staphb/genoflu genoflu.py -v
genoflu.py: version 1.03

However, we I try to run the program against test-genome-A1.fasta, I see the following error
$ pwd
/home/ad_vhapalmostaa0/GenoFLU
$ ls
test-genome-A1.fasta
$ docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data1 staphb/genoflu genoflu.py -f test-genome-A1.fasta -i /data1

genoflu.py set arguements:

        FASTA:  test-genome-A1.fasta
        FASTA_dir:  /data1
        cross_reference:  None
        sample_name:  None
        debug:  False

Traceback (most recent call last):
  File "/opt/conda/bin/genoflu.py", line 342, in <module>
    genoflu = GenoFLU(FASTA=FASTA_abs_path, FASTA_dir=FASTA_dir, cross_reference=cross_reference, sample_name=args.sample_name, debug=args.debug)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/bin/genoflu.py", line 135, in __init__
    with open(FASTA_name, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test-genome-A1.fasta'

**Comment by erinyoung** [comment]
The default work directory for containers pulled from StaPH-B's repository is `/data`, but it looks like your fasta file is in /data1.


What happens if you run the full path of your fasta file?
```
docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data1 staphb/genoflu genoflu.py -f /data1/test-genome-A1.fasta -i /data1
```

**Comment by AnoshMostaghimi** [comment]
Sorry, and thank you. I did not know about the default work directory being /data.

Upon changing the location to /data I now see the following:

$ docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data staphb/genoflu genoflu.py -f test-genome-A1.fasta -i /data
cat: write error: Broken pipe

genoflu.py set arguements:

        FASTA:  test-genome-A1.fasta
        FASTA_dir:  /data
        cross_reference:  None
        sample_name:  None
        debug:  False


Traceback (most recent call last):
  File "/opt/conda/bin/genoflu.py", line 347, in <module>
    genoflu.blast_hpai_genomes()
  File "/opt/conda/bin/genoflu.py", line 222, in blast_hpai_genomes
    df = pd.read_excel(self.cross_reference)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/pandas/io/common.py", line 472, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

**Comment by erinyoung** [comment]
Hmm... I'm unsure what the `-i` flag does in your command. What happens with you drop it and just run

```
docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data staphb/genoflu genoflu.py -f test-genome-A1.fasta
```

**Comment by AnoshMostaghimi** [comment]
Thank you, removing -i flag fixed it. Really appreciate your help!

**Comment by AnoshMostaghimi** [comment]
According to the GenoFLU documentation, running the test-genome-A1.fasta should generate the following:

test-genome-A1 Genotype --> A1: PB2:ea1, PB1:ea1, PA:ea1, HA:ea1, NP:ea1, NA:ea1, MP:ea1, NS:ea1

However, the output that I see is different ... Is something else needs to be tweaked?

$ docker run -v /home/ad_vhapalmostaa0/GenoFLU:/data staphb/genoflu genoflu.py -f test-genome-A1.fasta

genoflu.py set arguements:

        FASTA:  test-genome-A1.fasta
        FASTA_dir:  None
        cross_reference:  None
        sample_name:  None
        debug:  False



test-genome-A1 Genotype --> Not assigned: Only 0 segments >98% match found of total 2 segments in input file:

**Comment by erinyoung** [comment]
Hmmm...

I can't seem to replicate your error:

This is what I did:
```
# download test fasta file
wget -q https://raw.githubusercontent.com/USDA-VS/GenoFLU/main/test/test-genome-A1.fasta

# running the command
docker run -v $(pwd):/data staphb/genoflu genoflu.py -f  test-genome-A1.fasta -n sample
```

This was the output that I got:
```
genoflu.py set arguements:

	FASTA:  test-genome-A1.fasta
	FASTA_dir:  None
	cross_reference:  None
	sample_name:  sample
	debug:  False



sample Genotype --> A1: PB2:ea1, PB1:ea1, PA:ea1, HA:ea1, NP:ea1, NA:ea1, MP:ea1, NS:ea1
```

And I got both expected files:
- sample_2024-11-14_22-54-38_stats.tsv 
- sample_2024-11-14_22-54-38_stats.xlsx

**Comment by AnoshMostaghimi** [comment]
Thank you.  Everything it is working. The problem was with my copy of the downloaded test-genome-A1.fasta

**Comment by erinyoung** [comment]
I hate it when that happens!!!
