### ISSUE TITLE
LABEL container.version --> LABEL dockerfile.version

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#118]
`LABEL container.version` is super vague. It should be `LABEL dockerfile.version`. Intended for tracking multiple versions of a dockerfile for a single program (and it's single version).

 For example if I had to make adjustments to the SPAdes 3.14.1 dockerfile (for which there is only one dockerfile version currently), I would bump to `LABEL dockerfile.version=2`

**Comment by erinyoung** [comment]
Could you give an example of how you want this to look?

**Comment by kapsakcj** [comment]
`LABEL dockerfile.version="1"` for the first iteration of a dockerfile. Then if you had to tweak the dockerfile at a later date, but not change the version of the actual program (SPAdes or whathave you), then I would change it to `LABEL dockerfile.version="2"` when commiting the edited dockerfile to the repo.

IMO semantic versioning isn't necessary here because I don't expect dockerfiles to change much once they are running smoothly and I would like to keep it simple.

Happy to hear your thoughts on this.

**Comment by erinyoung** [comment]
The label is correct in the template, right?

https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile

@kapsakcj , do you think we need to add/change labels?

**Comment by kapsakcj** [comment]
Yes, the template has the correct LABEL (`dockerfile.version`). 

The only slight change for the template would be something like this, if multiple people are maintainers or authors of the dockerfile:

```Dockerfile
LABEL maintainer1="Anders Goncalves da Silva"
LABEL maintainer1.email="andersgs@gmail.com"
LABEL maintainer2="Curtis Kapsak"
LABEL maintainer2.email="curtis.kapsak@theiagen.com"
```

**Comment by erinyoung** [comment]
I want to ensure that each docker image has the recommended labels, so I added a check in https://github.com/StaPH-B/docker-builds/pull/499. 

I had a difficult time adding wildcards when using docker inspect to look at labels, so I'm going to recommend that the first maintainer is maintainer and the nth maintainer is maintainer$n. So the recommendation would look like this:

```Dockerfile
LABEL maintainer="Anders Goncalves da Silva"
LABEL maintainer.email="andersgs@gmail.com"
LABEL maintainer2="Curtis Kapsak"
LABEL maintainer2.email="curtis.kapsak@theiagen.com"
```

**Comment by erinyoung** [comment]
I think we can close this issue now.
