### ISSUE TITLE
add shigatyper

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#133]
@AndrewLangvt whenever you get a chance 😃

**Comment by erinyoung** [comment]
I was trying to use the [biocontainers one on quay](https://quay.io/repository/biocontainers/shigatyper?tab=tags), and it's missing samtools

**Comment by kapsakcj** [comment]
Addressed in #321 , but we need to deploy the image to dockerhub & quay. Going to leave this open until that happens.

OK to trigger the deploy-shigatyper workflow?

**Comment by kapsakcj** [comment]
I triggered the `deploy-shigatyper.yml` workflow manually, but it failed since quay_username and quay_robot_token were not provided. Log here: https://github.com/StaPH-B/docker-builds/runs/5796541592?check_suite_focus=true

These inputs should be optional, so I didn't expect it to fail.

We can either add those inputs to `deploy-shigatyper.yml` & re-trigger the workflow or we can somehow adjust the `build-to-deploy.yml` to truly make those inputs optional and allow the dockerhub deployment to proceed when quay_username and quay_robot_token are not provided as inputs

**Comment by kapsakcj** [comment]
Closing as I've updated the `deploy-shigatyper.yml` workflow and successfully pushed the docker image to both dockerhub and quay

GH actions log here: https://github.com/StaPH-B/docker-builds/actions/runs/2100137656
