### ISSUE TITLE
add kraken2 v2.0.9-beta

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#139]
https://github.com/DerrickWood/kraken2/releases/tag/v2.0.9-beta

**Comment by kapsakcj** [comment]
Have a dockerfile ready, but can't test at work since the FTP site is blocked...will test at home
```Dockerfile
# base image
FROM ubuntu:xenial

# for easy upgrade later. ARG variables only persist during build time.
ARG K2VER="2.0.9-beta"

LABEL base.image="ubuntu:xenial"
LABEL dockerfile.version="1"
LABEL software="Kraken2"
LABEL software.version="2.0.9-beta"
LABEL description="Taxonomic sequence classifier"
LABEL website="https://github.com/DerrickWood/kraken2"
LABEL license="https://github.com/DerrickWood/kraken2/blob/master/LICENSE"
LABEL maintainer="Curtis Kapsak"
LABEL maintainer.email="pjx8@cdc.gov"

# install dependencies and cleanup apt garbage
RUN apt-get update && apt-get -y install \
 wget \
 zlib1g-dev \
 make \
 g++ && \
 rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get autoclean

# DL Kraken2, unpack, and install
RUN wget https://github.com/DerrickWood/kraken2/archive/v${K2VER}.tar.gz && \
  tar -xzf v${K2VER}.tar.gz && \
  rm -rf v${K2VER}.tar.gz && \
  cd kraken2-${K2VER} && \
  ./install_kraken2.sh . && \
  mkdir /data

ENV PATH="$PATH:/kraken2-${K2VER}" \
    LC_ALL=C

WORKDIR /data

# DL MiniKraken2_8GB database. Built from RefSeq bacteria, archaea, and viral libraries. No human.
RUN mkdir /kraken2-db && \
 cd /kraken2-db && \
 wget ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/minikraken_8GB_202003.tgz && \
 tar -zxf minikraken2_8GB_202003.tgz && \
 rm -rf minikraken2_8GB_202003.tgz
```

**Comment by kapsakcj** [comment]
Will likely need to pull the K2 minikraken database from a new URL. https://benlangmead.github.io/aws-indexes/k2

**Comment by kapsakcj** [comment]
Hey @erinyoung I've almost wrapped up a dockerfile for this one, no need to duplicate effort here. I'm planning to use the minikraken database that includes human sequences from Ben's website linked above: 

Minikraken v2 | Refseq: bacteria, archaea, viral, human

Also going to create a separate dockerfile that has the database lines commented out and keep it under a different tag on dockerhub: `staphb/kraken2:2.0.9-beta-no-db`

**Comment by kapsakcj** [comment]
added the dockerfile for the version with the minikraken database included here: https://github.com/StaPH-B/docker-builds/commit/e80513aa5b4a5552ced2260e7983fb5568794a7c

Praying that it will build on dockerhub, despite the size of the database - 8GB uncompressed 😟

**Comment by erinyoung** [comment]
Even if it builds on dockerhub, the end user might not be able to download and unpack it 😨

**Comment by kapsakcj** [comment]
Agreed. It did build and worked locally for me but I don't think it's sustainable. Definitely a bad idea to keep large db's inside these images.
