### ISSUE TITLE
add pangolin 2.0.5?

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#141]
https://github.com/cov-lineages/pangolin/releases/tag/v2.0.5

**Release notes**
- Memory issues resolved (thanks ArtPoon!)
- prep package removed from repo, now hosted at cov-support
- shebang fix

Hi @andersgs Not sure if you or anyone else is interested in upgrading or not, just FYI. I'd rather not tackle this one because I'm not familiar with the program and the associated lineage database and I don't want to screw it up 😀

**Comment by andersgs** [comment]
I'll try to get to it today. 🙂

**Comment by kapsakcj** [comment]
No rush! Just wanted to make you aware of the new release :) Thanks again for contributing to this repo!
