### ISSUE TITLE
add NanoPlot v 1.33.0 when it is released

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#148]
Wouter removed `orca` as a dependency for NanoPlot v1.33.0+ and I believe is releasing this version via PyPI soon. 

`orca` is replaced with this https://github.com/plotly/Kaleido#docker-compatibility

original discussion: https://github.com/wdecoster/NanoPlot/issues/174#issuecomment-691283984

**Comment by wdecoster** [comment]
It's on PyPI: https://pypi.org/project/NanoPlot/

**Comment by kapsakcj** [comment]
Done in https://github.com/StaPH-B/docker-builds/commit/770618d2ef40a94822748165f339ba25c9b1dd60

Building on dockerhub now... image can be `docker pull`'d with `staphb/nanoplot:1.33.0` or `staphb/nanoplot:latest`
