### ISSUE TITLE
your sopport

### ISSUE THREAD

**Issue by Chris091089** [StaPH-B/docker-builds#158]
Good evening, the main reason for the following text is to request your support because I am using your SeqSero2 image however when I enter the command line docker run seqsero2 SeqSero2_package.py -p 10 -t 2 -i ./seqsero2/* R *; I get the following error subprocess.CalledProcessError: Command 'bwa mem -k 17 -t 10 H_and_O_and_specific_genes.fasta BB43_S1_R1.fastq.gz BB43_S1_R2.fastq.gz> BB43_S1_R1.fastq.gz.sam 2 >> data_log.txt' returned non- zero exit status 1.

**Comment by kapsakcj** [comment]
Hi, based on your command it looks like you are not mounting a volume using `docker run -v /local-path:/data [...]`. Basically your data is not making it inside the container, so bwa mem throws an error. If your data is in your present working directory, then you can mount that directory to `/data` inside the container like so `docker run -v $PWD:/data [...]`

I recommend you checking out our guide for more tips on running the containers https://staph-b.github.io/docker-builds/run_containers/

**Comment by kapsakcj** [comment]
@Chris091089 Were you able to get the SeqSero2 image to run?

**Comment by Chris091089** [comment]
yes, thank you very much for your support

**Comment by kapsakcj** [comment]
Awesome!
