### ISSUE TITLE
automated testing idea: include SARS-CoV2 genomes/fastas

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#163]
I think it would be a good idea to have a couple of SARS-CoV2 assemblies/consensus sequences available in the repo to aid in automated testing of COVID19 related tools. Tiny genome = tiny fasta = ideal for automated tests.

Perhaps the Hu-1 strain, maybe a B.1.1.7, other important ones?

could test these tools:
  * pangolin
  * VADR
  * iVar (? not sure on this one)
  * others?

e.g. 
`/tests/SC2-test-genomes.fasta` would have something along the lines of...
```
>Hu-1
ATCGAGC....
>B.1.1.7
CTATCGA...
```

First use TravisCI to build the docker image (`docker build -t pangolin:2.1.6 pangolin/2.1.6`) & bash scripts to test it
`/tests/pangolin.sh`
```bash
#!/bin/bash
# test for pangolin
set -e

docker run pangolin:2.1.6 pangolin --threads 2 --outdir pangolin-test /tests/SC2-test-genomes.fasta
```

**Comment by kapsakcj** [comment]
VIBRANT too?

**Comment by kapsakcj** [comment]
ok, maybe drop VADR from the list. It requires a lot of RAM to run and that might not be feasible on a TravisCI VM.

**Comment by erinyoung** [comment]
I have some bam files, fastq, and fastas that I could upload. Where do you want me to put them?

**Comment by kapsakcj** [comment]
Great. I think either directly in `/tests` or a sub-folder within tests would be fine.

Side note: We have unintentionally abused TravisCI to the point where the StaPH-B organization has run out of "free credits" for automated tests. Partly because it would run tests every time a commit was pushed to `master` branch; partly because our automated tests would take a LONG time to run (anywhere from 15-50 minutes) which ate through all of our free credits

Now may be a good time to look into GitHub Actions unless we want to start forking out some money for the service 😬 

So I appreciate you taking the initiative to adding these files, but just be aware that TravisCI tests won't run

@k-florek @kevinlibuit FYI - this impacts staphb_toolkit too unfortunately ☹️

**Comment by k-florek** [comment]
@kapsakcj This is not ideal. Do the "free credits" replenish? I really don't think TraivsCI is built for what we are attempting to use it for i.e. testing memory or cpu intensive (intensive meaning anything that runs for >5 min on 1 cpu) tools or workflows (at least not the free version). We have held off on using TravisCI as anything more than a check to make sure the staphb-toolkit menu works because of this.

One suggestion I have is to put bams, fastqs, and fastas into a container with scrips for testing the various tools you want to validate and label it as a testing kit. Then you or the user can grab the testing kit and tool container and run the necessary scrips. Then we just adopt a practice that before pushing new containers you should use the test kit to validate them.

**Comment by kapsakcj** [comment]
Agreed. I think we were a bit overzealous in using TravisCI for testing the docker image build process. I like your idea of creating a "testing kit" container and running tests locally. 

> Do the "free credits" replenish?

No, unfortunately they do not replenish. It looks like we could apply for special OSS credits, though I'm not sure how likely we'll get approved for credits. I'm not sure what kind of OSS these credits typically go to. https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by kapsakcj** [comment]
So I think GitHub Actions may be a good replacement for TravisCI. After some furious googling, it seems that for free github accounts (including organizations e.g. StaPH-B org) and public repositories there is no limit on the number of minutes used per month for GitHub Actions workflows. I don't know if this will stay like this long-term, but there's a good chance it will stay with Microsoft backing Github

https://github.community/t/for-public-repositories-is-there-a-monthly-limit-on-minutes/129017

official docs - https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

I keep checking the StaPH-B organization's usage for GH Actions, and it's showing 0 minutes used, despite me running a workflow repeatedly for the last 3 days

Also, github offers documentation on how to best transition from TravisCI to GH Actions https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by erinyoung** [comment]
I found a SARS-CoV-2 sample that had a small enough file size to upload to the repository. It's publicly available data, so the human reads have already been scrubbed.

**Comment by kapsakcj** [comment]
Wanted to jot this down before I forget about it...

So now with VADR v1.2 & it's lowered memory requirements (64G -> 2G RAM per CPU thread), it would be feasible to run automated tests for the VADR container in a GH Actions workflow. Plus with the added multithreading functionality, it runs much faster than previous versions too.

Two scripts are provided with VADR that helps test the installation and functionality of VADR. Inside the container, they are located at:

`/opt/vadr/vadr/testfiles/do-all-tests.sh`
and
`/opt/vadr/vadr/testfiles/do-install-tests-local.sh`

The ideal Standard Output messages of each are as follows. (only showing last 10 lines of STDOUT for brevity)

for `do-install-tests-local.sh`:
```
$ tail vadr.1.2-do-install-tests-local.STDOUT.txt
# List of executed commands saved in:                  vt-d5-local.vadr.cmd
# List and description of all output files saved in:   vt-d5-local.vadr.list
#
# All output files created in directory ./vt-d5-local/
#
# Elapsed time:  00:00:40.74
#                hh:mm:ss
#
[ok]
Success: all tests passed [do-install-tests-local.sh]
```
And for `do-all-tests.sh`:
```
$ tail vadr.1.2-do-all-tests.STDOUT.txt
# List and description of all output files saved in:   vt-iss33-longdesc.vadr.list
#
# All output files created in directory ./vt-iss33-longdesc/
#
# Elapsed time:  00:00:04.68
#                hh:mm:ss
#
[ok]
Success: all tests passed [do-issue-tests.sh]
Success: all tests passed [do-all-tests.sh]
```


Additionally, we could test the functionality with the B.1.1.7 fasta file that Erin kindly provided in the docker-builds repository code: `/tests/SARS-CoV-2/SRR13957123.consensus.fa`. I'm also open to adding genomes for other common lineages, e.g. P.1, B.1.526, etc.

And since we have to migrate away from Travis, it would be prudent to build these tests into the GH Actions testing framework in PR #184

**Comment by rpetit3** [comment]
Late to the party, but here's a good repo with SC2 test data: https://github.com/nf-core/test-datasets/tree/modules

**Comment by erinyoung** [comment]
I think we need to be wary of file sizes that we use for testing. We don't want the repo to get too large, but with the current method of testing, relevant files should be included in the same directory as the Dockerfile. If they are going to be used by multiple tools, I think they may need to be pulled via wget, which shouldn't be too bad.

**Comment by k-florek** [comment]
Between the github test build actions and [https://github.com/StaPH-B/docker-builds/tree/master/datasets-sars-cov-2/0.6.2](https://github.com/StaPH-B/docker-builds/tree/master/datasets-sars-cov-2/0.6.2) I feel like this issue has been addressed.

@kapsakcj @erinyoung Can we close this issue?

**Comment by kapsakcj** [comment]
Yes, I'm good to close this issue

**Comment by erinyoung** [comment]
I'm good. I'll close it.
