### ISSUE TITLE
Can't build artic-ncov2019-medaka image from Dockerfile

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#170]
@AbigailShockey 
May need to clone artic repo from specific commit (line 24) as current repo has unified nanopore & medaka environments, i.e. can't build from /artic-ncov2019/environment-medaka.yml as this file no longer exists

**Comment by AbigailShockey** [comment]
Testing the fixes now

**Comment by kapsakcj** [comment]
Hey y'all, this probably belongs in a separate issue, but I noticed that artic-ncov2019-medaka and artic-ncov2019-nanopolish docker images aren't listed on the main README in the table. 

Could one of you add those to the README in a pull request at some point?

**Comment by AbigailShockey** [comment]
On it!

**Comment by kapsakcj** [comment]
❤️
