### ISSUE TITLE
Bedtools update

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#172]
There's a new version of bedtools available.

**Comment by kapsakcj** [comment]
Thanks for the heads up. This one should be pretty easy to update. I'm happy to do it at some point this week if you don't get to it.

https://github.com/arq5x/bedtools2/releases/tag/v2.30.0

**Comment by kapsakcj** [comment]
Gah, OK it's not so simple. There is no static binary for v2.30.0 on the GitHub releases page. May have to go through compiling and grabbing necessary dependencies

**Comment by kapsakcj** [comment]
I'm going to create an issue and see if they will add a static binary. Hopefully this docker image isn't urgently needed

**Comment by kapsakcj** [comment]
binary incoming 😃 https://github.com/arq5x/bedtools2/issues/897
