### ISSUE TITLE
add unicycler dockerfile 0.4.8 + deps for unicycler_polish script

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#185]
A bunch of extra tools/dependencies for this standalone script, but would be useful to have handy

https://github.com/rrwick/Unicycler/blob/main/docs/unicycler-polish.md

Could start with the existing dockerfile for 0.4.8 and add other dependencies. DEFINITELY need a variety of test data to ensure functionality of the various parts. May only be able to easily verify nanopore polishing

**Comment by kapsakcj** [comment]
Started making a dockerfile a while ago, I know there are some deps that are missing so this is a Work-In-Progress dockerfile. I've added the dockerfile to a the `unicycler-polish-dev` branch in https://github.com/StaPH-B/docker-builds/commit/a376ee183f173d24980f5e1d45fb20b595c61df5

Will pick back up eventually, but if anyone wants to have a crack at it, please go ahead!

**Comment by erinyoung** [comment]
Is this still an issue since we added [unicycler 0.5.0](https://github.com/StaPH-B/docker-builds/tree/master/unicycler/0.5.0)?

**Comment by kapsakcj** [comment]
Not really, no. 

I was interested specifically in the helper scripts included with Unicycler but that was a while ago and I don't plan on pursing this any time soon. 

I'm fine to close this issue unless there's someone out there that wants the ability to run those scripts too.

**Comment by erinyoung** [comment]
It's been a bit, so I don't think this is a current issue anymore. 

Feel free to re-open this issue.
