### ISSUE TITLE
update vadr container

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#193]
https://cspheres.slack.com/archives/C010Q9WCZJT/p1618328731221400

**Comment by kapsakcj** [comment]
I'm already working on it! thanks for creating the issue

**Comment by kapsakcj** [comment]
I'll announce in staph-b slack as well as the SPHERES slack once I have it ready. Just confirming some of the vadr test results with @nawrockie before I make the dockerfile available here and build the docker image on dockerhub.
