### ISSUE TITLE
Lyve-SET 1.1.4f image contains Lyve-SET 2.0.1

### ISSUE THREAD

**Issue by garfinjm** [StaPH-B/docker-builds#20]
The Lyve-SET 1.1.4f image currently contains Lyve-SET 2.0.1.

**Comment by kapsakcj** [comment]
haha oops. good catch. I blame @nwflorek since he wrote this Dockerfile :stuck_out_tongue_closed_eyes: 

Shouldn't be too difficult to fix. Would probably mean fixing these lines in the Dockerfile to grab the 1.1.4f release:
```Dockerfile
RUN wget https://github.com/lskatz/lyve-SET/archive/v2.0.1.tar.gz
RUN tar -xzvf v2.0.1.tar.gz;rm v2.0.1.tar.gz;mv lyve-SET-2.0.1 lyve-SET
```

Not sure if any of the dependencies would change or not, but I doubt it.

**Comment by nwflorek** [comment]
Woops, I'll fix this and update it.

**Comment by kapsakcj** [comment]
Thanks, Nick! Don't forget to trigger a new build on Docker hub once the Dockerfile is fixed.

**Comment by nwflorek** [comment]
Updated Dockerfile to use version v1.1.4f tested install and triggered rebuild.

**Comment by garfinjm** [comment]
Thanks! Ill give it a spin once it's built!
