### ISSUE TITLE
add lskatz/fasten

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#201]
https://github.com/lskatz/fasten

Never put a Rust tool in a container. Might be a little challenging, but definitely possible!

**Comment by lskatz** [comment]
You are welcome to duplicate it here since this is such a valuable resource but I have it on the repo now with a major thanks to @jhphan  https://github.com/lskatz/fasten/blob/master/Dockerfile

**Comment by erinyoung** [comment]
Your dockerfile looks great!

We've made some adjustments to the staphB docker repo, and now require dockerfiles to have two targets. Having a test target makes things easier for github actions testing.

Did you still have any interest in having StaphB to include fasten in their dockerhub repo?

**Comment by kimyoungw** [comment]
hi I know this has been closed a while, but could I request that fasten be added to StaphB's dockerhub repo? Thanks!

**Comment by kapsakcj** [comment]
Hi, sure we can add fasten to our repo, but if you want to get up and running today, I believe Lee has a docker image available on the github container registry: https://github.com/lskatz/fasten/pkgs/container/fasten

It make take us a little but of time to get this added - we welcome pull requests if you'd like to put together a dockerfile!

**Comment by kimyoungw** [comment]
Cheers thanks Curtis!
