### ISSUE TITLE
problems to run docker image

### ISSUE THREAD

**Issue by fedeserral** [StaPH-B/docker-builds#219]
Hi! I have some problems to run some docker image.
When I try to run spades with this command:

docker run -v $PWD:/data staphb/spades:latest spades

I have the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "spades": executable file not found in $PATH: unknown.
ERRO[0002] error waiting for container: context canceled

I dont know what it is happend. I run fastqc docker without any problem

Thanks!!

**Comment by kapsakcj** [comment]
try `spades.py` instead of `spades`

**Comment by fedeserral** [comment]
> try `spades.py` instead of `spades`

it is works!
Thanks you very much.
Regards!
