### ISSUE TITLE
ivar docker build - include script to convert TSV to VCF?

### ISSUE THREAD

**Issue by rpetit3** [StaPH-B/docker-builds#220]
Hello everyone! 

As your probably already know, ivar outputs variants in a TSV format, which you then have to convert to VCF (https://github.com/andersen-lab/ivar/issues/17).

I wanted to get your opinion on including and script in the ivar container build to convert the TSV to VCF. Here's a proposed solution: viralrecon's [ivar_variants_to_vcf.py](https://github.com/nf-core/viralrecon/blob/dev/bin/ivar_variants_to_vcf.py).

I personally think this would be useful, because it would allow VCF conversions to happen on the same task/process in workflows as ivar.

Thank you for your time!
Robert

**Comment by kapsakcj** [comment]
Yeah, that's fine, as long as it doesn't cause any major dependency clashes.

Could add a line to `pip3 install <things>` if there are python deps.

Thinking we add to this dockerfile, or perhaps make another one with a new tag https://github.com/StaPH-B/docker-builds/blob/master/ivar/1.3.1_Titan/Dockerfile

**Comment by kapsakcj** [comment]
Added in https://github.com/StaPH-B/docker-builds/commit/9915f1f3688be1357a45d363805ab9465e7102e5

and subsequently updated both samtools/htslib to 1.12 in https://github.com/StaPH-B/docker-builds/commit/97e5d3a3babd7dc5f8ec85f14e95f732e717e00e
