### ISSUE TITLE
add pull request template/checklist

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#227]
create a checklist or a template Pull Request to remember all the things I ask for when adding a dockerfile in a PR:
  - dir structure follows convention `/toolname/x.x.x/Dockerfile`?
  - edit `README.md`; add line for new tool or update line for existing tool
  - edit `Program_licenses.md`; add line for new tools
  - does your docker image build successfully?
  - does it produce a version number for relevant programs? `toolname --version` run properly?
  - does it produce results/output files that you would expect?
  - (eventually add this; will likely be optional) does your PR add automated tests? - this will be cool to have when I get around to looking at the testing framework in #184

**Comment by erinyoung** [comment]
I think I have something to address this in https://github.com/StaPH-B/docker-builds/pull/282

A corresponding pull request (https://github.com/StaPH-B/docker-builds/pull/280) is there to help with githhub actions.
