### ISSUE TITLE
Preference for an image based on pre-existing StaPH-B image

### ISSUE THREAD

**Issue by Antonia-Chalka** [StaPH-B/docker-builds#230]
I'm trying to build a container for Piggy (https://github.com/harry-thorpe/piggy), which requires an existing roary 3.12 installation.
Since StaPH-B already has an existing roary 3.12 image, using it as a base for a new piggy image seems the obvious solution.

Since I'd also like to share the piggy container via StaPH-B, I'm curious if you have any preference for building an image for a case like this. One solutions seems to be to base the piggy image from the pre-existing StaPH-B image (which may cause dependency issues in the future), like this:

```
FROM quay.io/biocontainers/roary:3.12.0--pl526h516909a_2

# metadata
LABEL base.image="quay.io/biocontainers/roary:3.12.0--pl526h516909a_2"
LABEL version="1"
LABEL software="Piggy"
LABEL software.version="1.5"
LABEL description="Pipeline for analysing intergenic regions in bacteria"
LABEL website="https://github.com/harry-thorpe/piggy"
LABEL maintainer="Antonia Chalka"
LABEL maintainer.email="s1438773@ed.ac.uk"

# install git
RUN apt-get -y update && apt-get -y install git

RUN git clone https://github.com/harry-thorpe/piggy.git

# add piggy executable to path
ENV PATH="/data/piggy/bin/:${PATH}"

#set working directory
WORKDIR /data
```

Alternatively, another option would be to copy the roary 3.12 dockerfile and credit the original roary docerfile creation (though I'm unsure how to go about formatting this):

```
FROM ubuntu:xenial

# metadata

#roary credits 
LABEL roary.image.maintainer="Curtis Kapsak"
LABEL roary.image.maintainer.email="pjx8@cdc.gov"
LABEL roary.image="quay.io/biocontainers/roary:3.12.0--pl526h516909a_2"

LABEL base.image="ubuntu:xenial"
LABEL version="1"
LABEL software="Piggy"
LABEL software.version="1.5"
LABEL description="Pipeline for analysing intergenic regions in bacteria"
LABEL website="https://github.com/harry-thorpe/piggy"
LABEL maintainer="Antonia Chalka"
LABEL maintainer.email="s1438773@ed.ac.uk"

# Roary installation copied from https://github.com/StaPH-B/docker-builds/blob/master/roary/3.12.0/Dockerfile

# install dependencies
RUN apt-get update && apt-get install -y bedtools \
                     cd-hit \
                     ncbi-blast+ \
                     mcl \
                     parallel \
                     prank \
                     mafft \
                     fasttree \
                     make \
                     curl \
                     cpanminus \
                     libxml-parser-perl \
                     libperlio-utf8-strict-perl \
                     libmoose-perl \
                     libgraph-perl

RUN cpanm LWP::Simple \
      Text::CSV \
      JSON \
      File::Slurp

RUN cpanm --force AJPAGE/Bio-Roary-3.12.0.tar.gz && \
      mkdir /data && \
      mkdir /kraken_db

# Piggy installation

# install git
RUN apt-get -y install git

RUN git clone https://github.com/harry-thorpe/piggy.git

# add piggy executable to path
ENV PATH="/data/piggy/bin/:${PATH}" \
 LC_ALL=C


#set working directory
WORKDIR /data
```

**Comment by kapsakcj** [comment]
Hi @Antonia-Chalka thanks for reaching out about this. We would welcome a dockerfile for piggy to this repository.

One point of clarification - biocontainers is a separate/distinct project than the StaPH-B/docker-builds project, where they take all bioconda recipes and create docker containers based off of them. While it is an awesome project, we have no control over those docker images and would prefer that you do not use their docker images as a base. It would be quite difficult for us to support/troubleshoot those docker images.

That being said I think either of your above examples would be ok, the first may be the simplest. You would just need to replace the FROM line with `FROM staphb/roary:3.12.0` and update the LABEL base.image line as well.

If you go with the second Dockerfile, you would have more discrete control of what is installed at image build time and would not be reliant on the `staphb/roary:3.12.0` docker image being available on dockerhub. (Though, we plan to keep this and all staphb docker images on dockerhub as long as possible!)

If you open a PR, myself or one of the other maintainers can review the dockerfile and help with formatting

**Comment by Antonia-Chalka** [comment]
Thank you for your quick response, as well as for catching that I acidentally linked to the biocontainers roary image (I was looking around for existing roary 3.12 containers and forgot to replace the biocontainer one with the StaPH-B version when creating my issue, my bad).

In any case, thank you for sharing your thoughts. Since I'm planning to submit this as part of the StaPH-B depository, having a depedency within another existing file shouldn't be too back, but wanted to make sure that was alright with you, just in case. I'll go ahead and submit a PL soon.

**Comment by kapsakcj** [comment]
ah ok, got it. Thanks for being willing to contribute here!

FYI, the dockerfile for roary 3.12.0 does not build successfully like it did 2 years ago ☹️ I just gave it a test since you may be building off the existing dockerfile.

See here for the end of the `docker build` output #232

Hopefully this isn't too bad to debug, but will take some trial/error to get perl dependencies installed properly.

**Comment by Antonia-Chalka** [comment]
Thanks for the heads up. The dockerhub images works just fine thankfully, so that's another reason to go with the first option 😅
