### ISSUE TITLE
add kraken to roary

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#254]
Roary has this cool [optional QC feature](https://github.com/sanger-pathogens/Roary#optional-dependencies) that uses kraken to determines what organism each gff file has.

Except... this means that the container needs kraken, which the [current container](https://github.com/StaPH-B/docker-builds/blob/master/roary/3.13.0/Dockerfile) does not have.

The container does create a `/kraken_db` directory, though.

**Comment by kapsakcj** [comment]
sure, we can get that added. Lots of copy/paste from here, I think https://github.com/StaPH-B/docker-builds/blob/master/kraken/1.1.1-no-db/Dockerfile

I thought there was a binary, but looks like I'm mistaken. We'll probably have to build kraken from source

**Comment by erinyoung** [comment]
I think the container that @kapsakcj created in https://github.com/StaPH-B/docker-builds/pull/260 will be good enough to cover this.

Thank you @kapsakcj !

**Comment by kapsakcj** [comment]
kraken1 has been added to roary 3.13.0 docker image in #260 

updating docker images on dockerhub and quay: `staphb/roary:3.13.0` and `staphb/roary:latest`
