### ISSUE TITLE
How do you ensure the integrity or stability of all versions?

### ISSUE THREAD

**Issue by jrichardsz** [StaPH-B/docker-builds#272]
This repository is awesome. Is a collection of tools ready to use by anyone in the world. I see a lot of tools with multiple versions. How do you ensure that new tool:1.2.3  don't break anything in its folder or another tools?

**Example**: Someone performs a pull request with a lot of lines in several folders. 
- How can we be sure that these changes are fine?
- How can we be sure that another touched folders continue to work?

I think your current solution is that some human tries locally the changes and manually perform some tests to verify that everything is working. But can the human test every tool with, its versions, scenarios, etc?

From a software engineering perspective,  there is one answer: Unit Test & Code Coverage

With this approach, you will have an automatic report (1 to 5 mins without human) which tells you if some tool is failing due to some modifications before the merge of pull request. This kind of technique will scan all tools and its versions, looking if some **predefined** behavior **started to fail**

Reports could be like:

**Driven to features and its scenarios**
![](https://unitjs.com/assets/img/screen_console_unitjs_and_mocha_demo2.png) 

**Drive to files**
![](https://i.stack.imgur.com/ooy7Y.png)

### Understand what is "unit testing"
- Check this [sample](https://gist.github.com/jrichardsz/f6844d6497f0a1e6b600e8603919268f)
- http://www.cs.toronto.edu/~yijun/csc408h/handouts/tutorial4x4.pdf
- https://jitm.ubalt.edu/XXIX-2/article4.pdf
- https://personal.utdallas.edu/~lxz144130/cs6367/cs6367-lec2.pdf
- https://resources.sei.cmu.edu/asset_files/CurriculumModule/1989_007_001_15692.pdf

### Define features and scenarios of each tool/version that must be followed
- Check [this](https://docs.behat.org/en/v2.5/guides/1.gherkin.html) to understand what is the relationship between feature and scenario in quality software topics.
- Descriptive example for **abricate** tool:
```
Feature: Abricate tool 

  Scenario: 
    Given a valid assembly.fa file
    Then a tap-separated output file should be created
    And it should contain at least 3 columns : sequence, start, end
```

- Code example for **abricate** tool:
```
describe('#Abricate tool', function () {
    it('should contain at least 3 columns : sequence, start, end', function () {
        let outputFile = abricateDockerizedToolHttpService("test/assembly.fa");
        expect(outputFile).to.be.not.null();
        expect(outputFile.columnsCount()).to.equal(3);
        //etc
    });
});
```

### Define how standardize the response of all tools. 

- I propose a basic http service
- Using docker, invoke the tests provided by the tool itself and abort the build if test fails
 
### Choose some framework to write the unit tests.
- I propose mocha or jest with nodejs language

### Contact

Let me know is this idea makes sense for you to ensure the integrity off all your collection tools. It would be a pleasure to share some knowledge of software engineering with you and to help with a grain of sand to the **StaPH-B** team. 

Richard,
Fullstack Open Source Architect, devops expert & consultant.
https://stackoverflow.com/users/3957754/jrichardsz

**Comment by k-florek** [comment]
Hi @jrichardsz thanks for the post and sorry for the delay in responding to this. We have all been quite overwhelmed with the emergence of Omicron so a lot of these projects have been slowed.

I agree 100% with your assessment. As you can see looking through our issues and comments Unit Testing has been a concern for awhile and something we have had a few discussions on how to implement properly. One of the biggest challenges around building unit tests for bioinformatic tools is the computational requirements for many of these tools. Many of the tools need more CPU/Memory than GitHub Actions allow for so true unit testing can sometimes be a challenge. We have a few ideas on how to deal with these limitations but we are moving slowly on developing the contribution guidance.

As for how we handle version control you might have noticed that we have separate subfolders for each version. This allows us to maintain a distinct dockerfile/image for each version. Older versions of tools are often used and supported as many workflows may be require a specific version of a tool to function correctly or provide and accurate result.

All of this is to say we completely agree with your points here and this is something we are working to establish better guidance for contributing to make everyone's job easier!
