### ISSUE TITLE
Label standards?

### ISSUE THREAD

**Issue by jlumpe** [StaPH-B/docker-builds#277]
Is there any sort of standard or schema container labels are supposed to conform to?

**Comment by kapsakcj** [comment]
No strict standards per se, but we have a dockerfile template you could use as an example/model https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile

Feel free to include any additional & relevant LABELs that you think are important to include

**Comment by jlumpe** [comment]
Thanks!
