### ISSUE TITLE
Broken formatting on StaPH-B webpage

### ISSUE THREAD

**Issue by SarahNadeau** [StaPH-B/docker-builds#283]
The markdown formatting I used for collapsable sections in #280 doesn't work on the StaPH-B website: 

<img width="1161" alt="Screen Shot 2022-01-25 at 10 43 24 AM" src="https://user-images.githubusercontent.com/30396464/151009729-0ca27dd5-d74a-4a46-963b-e6168e1270cc.png">

I can do a quick-fix by removing the collapsable section formatting, but I'm not sure where to put the image resources so they display properly.

**Comment by k-florek** [comment]
@SarahNadeau The issue wasn't your code but the CSS. I fixed the issue and set the corrected the styling. Thanks for adding to the documentation!

**Comment by SarahNadeau** [comment]
Great! I did notice one other messed-up bit still - maybe here you just want to remove the formatting?
<img width="1190" alt="Screen Shot 2022-01-25 at 12 23 12 PM" src="https://user-images.githubusercontent.com/30396464/151027354-23ecc1b8-638c-4072-b076-6b948bf2e522.png">
