### ISSUE TITLE
[Bug]: docs formatting - contributing guidelines

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#284]
### Contact Details

kapsakcj@gmail.com

### What container were you trying to use, and how were you attempting to use it?

The recent changes to contributing guidelines and/or GitHub Page dependencies may have caused in-line code snippets & code blocks to no longer be formatted as code. 

See here, under best practices, ➡️ Minimize the number of layers
https://staphb.org/docker-builds/make_containers/

Not a big deal, but would be good to fix at some point.

Those `<detail> </detail>` drop-down blocks are sensitive to returns (more returns the better) so it may just need a return somewhere.

![image](https://user-images.githubusercontent.com/8172086/151297640-447b68b0-a9b1-4bbb-9880-5b9d9909c1a3.png)

**Comment by k-florek** [comment]
Thanks for finding this!!
