### ISSUE TITLE
[Repo Request]: bug - pull request template checklist looks triplicated?

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#287]
### What functionality is this repo missing?

Not missing functionality, but the PR template looks to be triplicated on accident. See the markdown template on `master` branch, recently brought in by PR #282 

https://github.com/StaPH-B/docker-builds/blob/master/.github/PULL_REQUEST_TEMPLATE.md

CC @erinyoung were there un-pushed commits on your side perhaps?

either way, should be simple to correct. I just wasn't sure which of the 3 blocks of checklists were the one's intended for use

**Comment by kapsakcj** [comment]
NVM. disregard. I cannot read. I didn't realize they were separated by conditionals.

**Comment by erinyoung** [comment]
I thought about doing the same thing as with the pull requests as with the issues, but it was difficult to test.

**Comment by kapsakcj** [comment]
understood. No worries, I figured it out after reading through the conditionals.

@kevinlibuit mentioned that the PR checklist was a little intimidating to him at first, but helpful in the end
