### ISSUE TITLE
Add github actions test for each tool

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#297]
Because my free time is limited, I don't know how many currently existing containers will get a github actions workflow.

Moving forward, however, each container should come with some sort of test.

Each dockerfile needs at least two different sections : the app section and the test section. The app section builds the dockerfile. The test section specifies a selection of commands to test the tool. 

- Files that are needing for testing should be included in the same directory as the dockerfile and be included into the test via COPY (do not use ADD). 
- Files that are too large to be included in github can be downloaded with curl or wget.

Please look at the [example template](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile) to see what this looks like

Then a corresponding yaml file needs to be included in `.github/workflows` named as `test-<tool>.yml`. 

An example that can be copied and pasted can be found at [.github/workflow-templates/test-template.yml](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/test-template.yml).

**Comment by SarahNadeau** [comment]
I'd love to tackle this for some images but I will need to re-work my approach. In my fork I was pushing test data through a whole sequence of tools, using the output of one as input for the next. That's not really in the spirit of unit tests, and anyways per #163 I guess you don't want test data stored in this repo that way.

Anyways, here are the tools I'll re-vamp my tests for in case anyone else is looking at this issue:

BBTools			35.94
Trimmomatic		0.39
FLASH			1.2.11
Kraken			1.0.0
Kraken2			2.0.8
SPAdes			3.13.0
BWA 			0.7.17
Samtools		        1.9
Pilon 			1.22
BEDTools		        2.27.1
MLST 			2.16
Barrnap			0.8
Prokka			1.14.3
NCBI-blast+		2.9.0
quast			5.0
DIAMOND		2.0.13
MUSCLE			3.8.425
FigTree			1.4.4
ClonalFrameML	1.12
Gubbins			3.1.4

**Comment by erinyoung** [comment]
I'm actually going to close this issue. 

All dockerfiles moving forward will have tests and readmes, but we don't think the effort to update all the old dockerfiles is worth the benefit. 

I'm not going to stop anyone from working on this, though.
