### ISSUE TITLE
[Request An Update]: Pilon

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#300]
### Contact Details

eriny@utah.gov

### What container needs an update?

Pilon version 1.24 is out. I created a dockerfile for it and was going to update the repo here, but then continued to run into 
1) memory issues (one of my samples needed >100G)
2) time issues (this same sample was only on round 2 of polishing after several days)

As such, I won't be using pilon and would be the wrong person to maintain the container. Since I worked on it, here's the dockerfile and readme for anyone interested in taking up the mantle. It's still in draft phase (no tests were added).

**Comment by erinyoung** [comment]
Basic README:

[README.md](https://github.com/StaPH-B/docker-builds/files/8119032/README.md)

Dockerfile (had to add the *txt extention to get to upload to github)
[Dockerfile.txt](https://github.com/StaPH-B/docker-builds/files/8119045/Dockerfile.txt)

**Comment by kapsakcj** [comment]
Closed via PR #624
