### ISSUE TITLE
[Request An Update]: update dataset-sars-cov-2 to v0.6.3

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#307]
### Contact Details

carrier pigeon

### What container needs an update?

the CDC datasets-sars-cov-2 docker image could use a quick update to the latest release v0.6.3

I can do this pretty easily, but am quite swamped with work at the moment. If anyone wants to take it on, please go for it!

**Comment by kapsakcj** [comment]
and it would be incredibly helpful if someone tested out the docker instructions listed here: https://github.com/CDCgov/datasets-sars-cov-2#conda

to test the functionality with the new version of the docker image

**Comment by kapsakcj** [comment]
branch started here: https://github.com/StaPH-B/docker-builds/commit/73cec5be9eaa697651d482e62b2aa761c1c34847

**Comment by erinyoung** [comment]
PR here : https://github.com/StaPH-B/docker-builds/pull/325
