### ISSUE TITLE
[Request An Update]: samtools/bcftools/htslib 1.15

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#314]
### Contact Details

curtis.kapsak@theiagen.com

### What container needs an update?

I know all of these containers are awesome, but...we could benefit from having Samtools/bcftools/htslib tools upgraded to 1.15

I have one small request to include `python3` in the `samtools:1.15` container to help with parsing some samtools outputs. would be best to `apt-get install --no-install-recommends python3` so that we aren't bringing in too many new python-related packages

Happy to take this on, right after I figure out how to push multiple docker image tags at once via GH actions workflow!

Use `ubuntu:focal` as base

**Comment by erinyoung** [comment]
I just barely saw this. I'll rework the samtools one to make sure it has python3.

**Comment by kapsakcj** [comment]
thank you so much!

**Comment by kapsakcj** [comment]
Taken care of in #315 . Thank you, Erin!
