### ISSUE TITLE
[Bug]: Freyja missing ps

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#335]
### What container were you trying to use, and how were you attempting to use it?

```
Command 'ps' required by nextflow to collect task metrics cannot be found
```

**Comment by erinyoung** [comment]
Also, how do you get update to work?

**Comment by kapsakcj** [comment]
Unfortunately it won't be an easy fix (at least I don't see an easy one).

I think this dockerfile will need an overhaul. the base is quite out of date and slow to build since it's using an old conda version. I'd want to upgrade to `mambaorg/micromamba:0.22.0` and use `micromamba` to build the conda env.

Running `apt update && apt install procps` requires user input to accept some things (even after setting `DEBIAN_FRONTEND=noninteractive`)

I can work on a PR, but right now pangolin 4.0.3 is my priority to get done

**Comment by erinyoung** [comment]
I am seeing a similar error when trying to use update. 

It makes me happy that it's not just me!

**Comment by kevinlibuit** [comment]
Error codes love company

**Comment by rpetit3** [comment]
The directory has to exist for `--outdir`, otherwise its not happy:
```
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/staphb/freyja:1.3.4 freyja update --outdir /data/freyja
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-x9fq9g8b because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/opt/conda/envs/freyja-env/bin/freyja", line 10, in <module>
Downloading a new global tree
    sys.exit(cli())
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/_cli.py", line 77, in update
    download_tree(locDir)
  File "/opt/conda/envs/freyja-env/lib/python3.10/site-packages/freyja/updates.py", line 11, in download_tree
    urllib.request.urlretrieve(url, treePath)
  File "/opt/conda/envs/freyja-env/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/freyja/public-latest.all.masked.pb.gz'
```

When the directory exists, it works fine for me (I think?):
```
mkdir freyja
docker run --rm -u $(id -u):$(id -g) -v ${PWD}:/data quay.io/staphb/freyja:1.3.4 freyja update --outdir /data/freyja 2>/dev/null
Downloading a new global tree
Getting outbreak data
Converting tree info to barcodes
/data/
Building barcodes from global phylogenetic tree
separating combined splits
checking for mutation pairs
Cleaning up
ls -lh freyja/
total 20M
-rw-r--r-- 1 robert_petit robert_petit 57K Apr 13 15:53 curated_lineages.json
-rw-r--r-- 1 robert_petit robert_petit 20M Apr 13 15:55 usher_barcodes.csv

```

**Comment by kevinlibuit** [comment]
So this is how I wrote the freyja_update WDL workflow and it did work locally, but that error is from the stdout when the same workflow is run in Terra.

There must be something about Cromwell and the how things are getting mounted that I'm not understanding

**Comment by kapsakcj** [comment]
Closing since `ps` was installed into the `staphb/freyja:1.3.4` docker image via #342

**Comment by kevinlibuit** [comment]
In case anyone stumbles upon this in the future: the issue I was running into on Terra was due to the [matUtils command executed ](https://github.com/andersen-lab/Freyja/blob/1a1d987690833288cc3d4a2b5957cb10f3fe2d34/freyja/updates.py#L18) in `freyja update` being killed when the VM ran out of memory. 

All is solved with increased RAM. 🐏
