### ISSUE TITLE
[Request An Update]: add fastq-scan 1.0.0

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#353]
### What container needs an update?

I know all of these containers are awesome, but... fastq-scan 1.0.0 would be nice to have 

https://github.com/rpetit3/fastq-scan/releases/tag/v1.0.0

I can take care of this one unless someone beats me to it

**Comment by jwarnn** [comment]
I can take care of this!

**Comment by kapsakcj** [comment]
Closed via #356
