### ISSUE TITLE
[Container Request]: EToKi

### ISSUE THREAD

**Issue by lskatz** [StaPH-B/docker-builds#354]
### Contact Details

gzu2@cdc.gov

### What tool are you looking for and why?

Heads up, I am trying to build a container for EToKi https://github.com/zheminzhou/EToKi

I hope to have it for you soon to look over.  Thank you!

**Comment by lskatz** [comment]
(doesn't work yet https://github.com/lskatz/docker-builds/blob/lskatz-etoki/EToKi/1.2/Dockerfile)

**Comment by lskatz** [comment]
Ok now it seems to work.  Thanks for any feedback.  https://github.com/lskatz/docker-builds/blob/lskatz-patch-1/etoki/1.2/Dockerfile

**Comment by erinyoung** [comment]
Just a minor thing in the readme, and then I think we've got a functional etoki container : https://github.com/StaPH-B/docker-builds/pull/357

**Comment by kapsakcj** [comment]
closed via #357
