### ISSUE TITLE
[Request An Update]: Pangolin (constellations)

### ISSUE THREAD

**Issue by garfinjm** [StaPH-B/docker-builds#367]
### What container needs an update?

The constelations version in the Pangolin container is causing some issues in our lab and at least one other lab in our region, the [v0.1.9](https://github.com/cov-lineages/constellations/releases/tag/v0.1.9) and [v0.1.10](https://github.com/cov-lineages/constellations/releases/tag/v0.1.10) updates fix a bug that causes genomes with lots of missing data to be mis-assigned as probable BA.x by Scorpio (some details here: https://github.com/cov-lineages/pango-designation/issues/584)

Thanks for all your work on this!

**Comment by kapsakcj** [comment]
I'll push a hotfix as soon as I'm able. thanks for raising the issue!

**Comment by kapsakcj** [comment]
I've made a dev branch with this change `cjk-pango-constellations-bugfix`. Have not built a new docker image yet though

But this issue has me a little worried: https://github.com/cov-lineages/pangolin/issues/449 

Are you seeing anything similar? Lots of samples being that were previously given lineages to "Unassigned"?

**Comment by kapsakcj** [comment]
@garfinjm the docker image is available on dockerhub and quay now: `staphb/pangolin:4.0.6-pdata-1.8-constellations-0.1.10` . Would love to hear more feedback on how it goes!

**Comment by garfinjm** [comment]
Here's a test on the 11 samples that I had posted in https://github.com/cov-lineages/pango-designation/issues/584 that were all originally mis-called as BA.3. Everything seems like it's working to me, thanks for putting together the new image!

**staphb/pangolin:4.0.6-pdata-1.8**
| taxon | lineage | conflict | ambiguity_score | scorpio_call                 | scorpio_support | scorpio_conflict | scorpio_notes                                                              | version        | pangolin_version |
|-------|---------|----------|-----------------|------------------------------|-----------------|------------------|----------------------------------------------------------------------------|----------------|------------------|
| A     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.54            | 0.07             | scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| B     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.46            | 0.04             | scorpio call: Alt alleles 25; Ref alleles 2; Amb alleles 26; Oth alleles 1 | SCORPIO_v0.1.8 | 4.0.6            |
| C     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.56            | 0.09             | scorpio call: Alt alleles 30; Ref alleles 5; Amb alleles 19; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| D     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.46            | 0.02             | scorpio call: Alt alleles 25; Ref alleles 1; Amb alleles 28; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| E     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.46            | 0.02             | scorpio call: Alt alleles 25; Ref alleles 1; Amb alleles 28; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| F     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.39            | 0.04             | scorpio call: Alt alleles 21; Ref alleles 2; Amb alleles 31; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| G     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.54            | 0.07             | scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| H     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.54            | 0.07             | scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |
| I     | BA.3    |          |                 | Probable Omicron (BA.3-like) | 0.54            | 0.07             | scorpio call: Alt alleles 29; Ref alleles 4; Amb alleles 21; Oth alleles 0 | SCORPIO_v0.1.8 | 4.0.6            |


**4.0.6-pdata-1.8-constellations-0.1.10**
| taxon | lineage    | conflict | ambiguity_score | scorpio_call                  | scorpio_support | scorpio_conflict | scorpio_notes                                                              | version     | pangolin_version |
|-------|------------|----------|-----------------|-------------------------------|-----------------|------------------|----------------------------------------------------------------------------|-------------|------------------|
| A     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.61            | 0                | scorpio call: Alt alleles 20; Ref alleles 0; Amb alleles 13; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| B     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.48            | 0                | scorpio call: Alt alleles 16; Ref alleles 0; Amb alleles 17; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| C     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.64            | 0                | scorpio call: Alt alleles 21; Ref alleles 0; Amb alleles 12; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| D     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.48            | 0                | scorpio call: Alt alleles 16; Ref alleles 0; Amb alleles 17; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| E     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.48            | 0                | scorpio call: Alt alleles 16; Ref alleles 0; Amb alleles 17; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| F     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.36            | 0                | scorpio call: Alt alleles 12; Ref alleles 0; Amb alleles 21; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| G     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.61            | 0                | scorpio call: Alt alleles 20; Ref alleles 0; Amb alleles 13; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| H     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.61            | 0                | scorpio call: Alt alleles 20; Ref alleles 0; Amb alleles 13; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |
| I     | Unassigned |          |                 | Probable Omicron (Unassigned) | 0.61            | 0                | scorpio call: Alt alleles 20; Ref alleles 0; Amb alleles 13; Oth alleles 0 | PUSHER-v1.8 | 4.0.6            |

**Comment by kapsakcj** [comment]
OK great, thanks for sharing. So these failed QC, but were still assigned BA.3 via scorpio in the older docker image?  (staphb/pangolin:4.0.6-pdata-1.8)

Are you running pangolin with lower-than-default `--max-ambig` ?

**Comment by garfinjm** [comment]
Yeah, these are all terrible genomes, but they were all called BA.3 which hasnt shown up yet in MN. I got really suspicious when I had 11 on a single run of 92 samples back in April. 

We are using a pretty barebones pangolin command:
```pangolin -t 1 --analysis-mode accurate --outfile pusher_!{fasta}.csv !{fasta}```
