### ISSUE TITLE
IRMA memory issue

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#371]
This is a condensed summary of an email chain that I was involved in.

IRMA v1.0.2 has memory issues when using it for SARS-CoV-2. It _should_ be fine for flu.

There is a pre-1.0.3 hotfix available, but you need to contact James A. Smagala (CDC) directly as it's currently not publicly available.

**Comment by erinyoung** [comment]
@jwarnn mentioned that this would be good to include in the documentation for IRMA v1.0.2

**Comment by jwarnn** [comment]
PR #372 updates the documentation to warn any unsuspecting user that peril awaits if you intend to use IRMA on Sars-Covid-2 samples.

**Comment by fanninpm** [comment]
I checked the [IRMA webpage](https://wonder.cdc.gov/amd/flu/irma/irma.html) today, and I saw that v1.0.3 was recently released with the fix for SARS-CoV-2.

**Comment by jwarnn** [comment]
Thanks for the update @fanninpm! I will create a new staphb docker container and submit a PR. When that is merged I will close this issue.

**Comment by kapsakcj** [comment]
thanks all!
