### ISSUE TITLE
[Request An Update]: amrfinderplus 3.10.36

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#426]
### What container needs an update?

https://github.com/ncbi/amr/releases

small bugfix included in this release. Dockerfile will likely be nearly identical to the next most recent version already in this repo

Happy to submit a PR when I get a chance

**Comment by erinyoung** [comment]
I created a PR for this : https://github.com/StaPH-B/docker-builds/pull/431
