### ISSUE TITLE
[Request An Update]: Samtools 1.16

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#437]
### What container needs an update?

Samtools/HTSlib/BCFTools 1.16 are now out.

I'll try to get to these containers by the end of next week, but I won't be offended if someone beats me to it.

**Comment by kapsakcj** [comment]
I've started a dev branch for these 3 `cjk-samtools`, I'll submit a PR shortly

**Comment by kapsakcj** [comment]
opened PR #438 to address this issue

**Comment by erinyoung** [comment]
thank you!
