### ISSUE TITLE
[Container Request]: gfastats

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#493]
### What tool are you looking for and why?

Here's the thing, I want to create a container for gfastats, but I want a feature that's been added recently. This feature isn't including in an official version (specifically, the indicator of circularity with `--seq-report`). 

Do I wait until they make a full version or create a container off of their most recent PR? (https://github.com/vgl-hub/gfastats/commits/main)

**Comment by kapsakcj** [comment]
if you need the container asap, then I would recommend going the route of `git clone --recursive`'ing the repo and then `git checkout <commit-hash>` to pin to the commit that includes the new feature

example: https://github.com/StaPH-B/docker-builds/blob/master/resfinder/4.1.11/Dockerfile

**Comment by kapsakcj** [comment]
Closed via PR #619
