### ISSUE TITLE
[Container Request]: add Pasty 1.0.2

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#497]
### What tool are you looking for and why?

for Pseudomonas aeruginosa serogrouping: https://github.com/rpetit3/pasty

takes assemblies as input, runs blast, reports a serogroup

Already available via bioconda & biocontainers, but would be good to add to our collection of containers as well

**Comment by kapsakcj** [comment]
I started working on this, will push my dev branch and start a PR once I'm done testing

**Comment by kapsakcj** [comment]
Will be addressed via #498

**Comment by erinyoung** [comment]
Thank you for the PR!
