### ISSUE TITLE
[Request An Update]: shovill

### ISSUE THREAD

**Issue by HarryHung** [StaPH-B/docker-builds#508]
### What container needs an update?

Please update the SPAdes included in shovill 1.1.0 if possible.

Currently SPAdes 3.14.1 is included, but 3.15.5 is more stable in my experience. 

Thank you.

**Comment by kapsakcj** [comment]
That's a great idea, thanks for submitting this issue.

The dockerfile needs a little bit of an overhaul and we could include a SPAdes upgrade along with the overhaul

**Comment by kapsakcj** [comment]
OK, I've created a dev branch `cjk-update-shovill-1.1.0` and have upgraded to spades 3.15.5 (as well as upgraded to samtools 1.16.1 and pilon 1.24).

I've pushed the docker image  to my personal dockerhub if you'd like to test it: `kapsakcj/shovill:1.1.0-updated-spades`

https://hub.docker.com/r/kapsakcj/shovill/tags

Passes the dependency check and I've assembled at least one Salmonella enterica sample successfully with both spades and skesa.

I would like to do more thorough testing (including adding to the test layer) before making a PR & overwriting the existing `staphb/shovill:latest` & `staphb/shovill:1.1.0` docker images

**Comment by HarryHung** [comment]
Just tested `kapsakcj/shovill:1.1.0-updated-spades`. I can confirm it is working fine with my 3 Streptococcus pneumoniae samples, while they would crash the current `staphb/shovill:1.1.0`. 

Thank you so much for the quick turnaround and I hope it will pass your remaining tests successfully. Looking forward to use this image in my currently developing pipeline.

**Comment by kapsakcj** [comment]
Great, thanks for the feedback! I'll ping back here and close the issue once we finalize the PR and overwrite the staphb/shovill docker image tags!

**Comment by kapsakcj** [comment]
Closed via PR #511 

I changed my mind, we ended up creating a new custom docker image tag for this new dockerfile version, in an effort to preserve the existing shovill 1.1.0 docker image. We overwrite the `staphb/shovill:latest` tag as well as creating a new one: 

`staphb/shovill:1.1.0-2022Dec` <-- please use this image tag to take advantage of the upgrades

The older docker image will be preserved under `staphb/shovill:1.1.0`

Thanks for the feedback and let us know if you come across any docker images that need updating!
