### ISSUE TITLE
[Request An Update]: update samtools to 1.16.1

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#513]
### What container needs an update?

https://github.com/samtools/samtools/releases/tag/1.16.1

Minor patch release for `samtools`. No critical changes/bug fixes to motivate an upgrade, but would be good regardless to add (updated) dockerfiles for this release of samtools, htslib, bcftools

Would be a great first contribution for someone new to take on!

(please use the samtools 1.16 dockerfile as a starting point. It should have everything you need 😏 )

**Comment by bjeong4** [comment]
Let me tackle this one first for 2023 APHL docker for bioinformatics workshop assignment.

**Comment by kapsakcj** [comment]
Hi Byeong - @shelby-bennett created a separate GitHub issue #549 and claimed samtools v1.16.1

Could you please choose another tool for the workshop?

**Comment by kapsakcj** [comment]
Closed via PR https://github.com/StaPH-B/docker-builds/pull/585
