### ISSUE TITLE
any2fasta - Missing app & test layer 

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#516]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [any2fasta Dockerfile](https://github.com/StaPH-B/docker-builds/tree/master/any2fasta) to be compatible with GitHub action workflows

**Comment by wchen190** [comment]
I would like to work on this one for the docker workshop.

**Comment by kapsakcj** [comment]
closed via PR #584
