### ISSUE TITLE
[Request An Update]: bedtools 2.30.0 missing app & test layer & README.md

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#517]
### What container needs an update?

App and test layer need to be added to [bedtools dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/bedtools/2.30.0/Dockerfile)

also needs a tool-specific README.md

**Comment by erinyoung** [comment]
I'm closing this issue because 2.31.0 has been released.
