### ISSUE TITLE
augur - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#520]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [augur Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/augur/16.0.3/Dockerfile) to be compatible with GitHub action workflows

[1:37](https://theiagen.slack.com/archives/D01TQPN2SSG/p1673645830631419)
any2fasta - Missing app & test layer

**Comment by DrB-S** [comment]
I would like to work on this one for the course.

**Comment by smarcellus16** [comment]
Has anyone claimed this one? If not, dibs!

**Comment by erinyoung** [comment]
The old Dockerfile is missing the app and test layer, but there's also a newer version of augur available (23.0.0). It'd probably be easier to create a Dockerfile for the new version.
