### ISSUE TITLE
[Request An Update]: trycycler 0.5.0 missing app and test layer

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#521]
### What container needs an update?

missing app & test layer in [trycycler dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/trycycler/0.5.0/Dockerfile)

**Comment by bjeong4** [comment]
let me attempt this task for 2023 Docker workshop.

**Comment by kapsakcj** [comment]
Closing this issue since the `app` and `test` stages are present in the dockerfile for trycycler 0.5.3 (will soon be added via PR #615)
