### ISSUE TITLE
bwa - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#522]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [bwa Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/bwa/0.7.17/Dockerfile) to be compatible with GitHub action workflows

**Comment by DOH-KEW4303** [comment]
I'll take this one on for the Docker workshop!

**Comment by DOH-KEW4303** [comment]
disregard already taken :)
