### ISSUE TITLE
canu-racon - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#523]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [canu-racon Dockerfile](https://github.com/StaPH-B/docker-builds/tree/master/canu-racon/2.0) to be compatible with GitHub action workflows and tool-specific README

**Comment by erinyoung** [comment]
I'm actually going to close this one because these two tools are now in separate Dockerfiles
