### ISSUE TITLE
canu - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#524]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [canu Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/canu/2.2/Dockerfile) to be compatible with GitHub action workflows

**Comment by bjeong4** [comment]
I have completed adding app and test layer.

**Comment by erinyoung** [comment]
Associated with https://github.com/StaPH-B/docker-builds/pull/253
