### ISSUE TITLE
cfsan-snp - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#528]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [cfsan-snp Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/cfsan-snp-pipeline/2.0.2/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by erinyoung** [comment]
Associated PR https://github.com/StaPH-B/docker-builds/pull/606
