### ISSUE TITLE
circlator - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#529]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [circulator Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/circlator/1.5.6/Dockerfile) to be compatible with GitHub action workflows

**Comment by erinyoung** [comment]
I'm going to close this, because there's actually a bug in the container that needs to be resolved. https://github.com/StaPH-B/docker-builds/issues/601

(Or I'm not using it correctly and I request the readme to be updated).
