### ISSUE TITLE
[Request An Update]: add sra-tookit 3.0.5; modernize dockerfile

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#532]
### What container needs an update?

The sratoolkit 2.9.2 dockerfile could be used as a starting point, but we should upgrade to v3.0.5 and download the pre-compiled binary. I tried it recently and **it just worked out of the box** 🎉 

The 2.9.2 dockerfile is missing an app and test layer though.

https://github.com/ncbi/sra-tools

also missing a tool-specific README.md

**Comment by erinyoung** [comment]
Thank you @Kincekara for working on this!
