### ISSUE TITLE
emmtypingtool - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#533]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [emmtypingtool Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/emmtypingtool/0.0.1/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by erinyoung** [comment]
Closed with https://github.com/StaPH-B/docker-builds/pull/593
