### ISSUE TITLE
fastqc - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#534]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [fastqc Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/fastqc/0.11.9/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by poojasgupta** [comment]
I would like to work on this one for the docker workshop.

**Comment by kapsakcj** [comment]
Sounds good, Pooja!

Closing this duplicate issue in favor of #546
