### ISSUE TITLE
fasttree - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#535]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [fasttree Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/fasttree/2.1.11/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by danielevansr** [comment]
I'll give FastTree a go! 
-Dan

**Comment by erinyoung** [comment]
Closed with https://github.com/StaPH-B/docker-builds/pull/594
