### ISSUE TITLE
filtlong

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#540]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [filtlong Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/filtlong/0.2.1/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by erinyoung** [comment]
https://github.com/StaPH-B/docker-builds/pull/588 addresses the test issue. There is no tool-specific readme at the moment. 

I'll assign this to myself.

**Comment by erinyoung** [comment]
Addressed in https://github.com/StaPH-B/docker-builds/pull/614
