### ISSUE TITLE
kma - Missing app & test layer

### ISSUE THREAD

**Issue by kevinlibuit** [StaPH-B/docker-builds#541]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [kma Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/kma/1.2.21/Dockerfile) to be compatible with GitHub action workflows and tool-specific README

**Comment by erinyoung** [comment]
PR created https://github.com/StaPH-B/docker-builds/pull/591/
