### ISSUE TITLE
[Docker Workshop]: kSNP3 

### ISSUE THREAD

**Issue by bdelavan** [StaPH-B/docker-builds#543]
### What container needs an update?

I know all of these containers are awesome, but...

**Comment by erinyoung** [comment]
This is a good one to update. Thank you!

**Comment by erinyoung** [comment]
Are you still working on this or should we close the issue?

**Comment by erinyoung** [comment]
Thank you for your participation in APHL's Docker workshop! I'm going to close this issue, but you are still more than welcome to create Dockerfiles for the StaPH-B/docker-builds repo.
