### ISSUE TITLE
[Docker Workshop]: working on iqtree2 v2.2.2 for Docker workshop

### ISSUE THREAD

**Issue by jcw349** [StaPH-B/docker-builds#544]
### What container needs an update?

I know all of these containers are awesome, but...trying out iqtree2

**Comment by jcw349** [comment]
I was able to replace the wget portion of the Dockerfile, reference local installation of iqtree v2.2.2.2 to get the Docker build to work.

`Sending build context to Docker daemon 26.41 MB
Step 1/16 : FROM centos:7
 ---> b5b4d78bc90c
Step 2/16 : ARG IQTREE2_VER="2.1.2"
 ---> Using cache
 ---> 8ca649d80476
Step 3/16 : LABEL base.image "centos:7"
 ---> Using cache
 ---> ddee23a8eaba
Step 4/16 : LABEL dockerfile.version "1"
 ---> Using cache
 ---> 544724eea580
Step 5/16 : LABEL software "IQ-Tree2"
 ---> Using cache
 ---> f0e0cd9ac6d2
Step 6/16 : LABEL software.version "2.2.2"
 ---> Using cache
 ---> 511c51d1fbd1
Step 7/16 : LABEL description "Efficient software for phylogenomic inference"
 ---> Using cache
 ---> 94df57e6232a
Step 8/16 : LABEL website "http://www.iqtree.org/"
 ---> Using cache
 ---> 704698337d9c
Step 9/16 : LABEL source.code.website "https://github.com/iqtree/iqtree2"
 ---> Using cache
 ---> 0e88b1ebb6ca
Step 10/16 : LABEL license "https://github.com/iqtree/iqtree2/blob/master/LICENSE"
 ---> Using cache
 ---> 2d1e89be82f8
Step 11/16 : LABEL maintainer "Curtis Kapsak"
 ---> Using cache
 ---> 12b61debcd02
Step 12/16 : LABEL maintainer.email "pjx8@cdc.gov"
 ---> Using cache
 ---> 7e7391a0ab4d
Step 13/16 : COPY iqtree2-2.2.2.2 /iqtree2-2.2.2.2
 ---> 8790434ef507
Removing intermediate container c060addf39d9
Step 14/16 : RUN mkdir /data
 ---> Running in 909d81f6ceee

 ---> ad36c6f27e21
Removing intermediate container 909d81f6ceee
Step 15/16 : ENV PATH "/iqtree-${IQTREE2_VER}-Linux/bin:${PATH}" LC_ALL C
 ---> Running in e22f4ac0fa6f
 ---> da55664d78f6
Removing intermediate container e22f4ac0fa6f
Step 16/16 : WORKDIR /data
 ---> 7f96537ef02d
Removing intermediate container 96dd9acba2f8
Successfully built 7f96537ef02d`

**Comment by erinyoung** [comment]
Closed with https://github.com/StaPH-B/docker-builds/pull/581
