### ISSUE TITLE
[Docker Workshop]: Building MultiQC version 1.14 

### ISSUE THREAD

**Issue by golden75** [StaPH-B/docker-builds#548]
### What container needs an update?

current version is not the latest, building version 1.14 as workshop project

**Comment by erinyoung** [comment]
Are you still working on this or should we close the issue?

**Comment by golden75** [comment]
I am still working on the workshop project. I just want to give another try to get it going.

**Comment by erinyoung** [comment]
Thank you for your participation in APHL's Docker workshop! I'm going to close this issue, but you are still more than welcome to create Dockerfiles for the StaPH-B/docker-builds repo.
