### ISSUE TITLE
[Docker Workshop]: bwa

### ISSUE THREAD

**Issue by cjalcorta** [StaPH-B/docker-builds#552]
### What container needs an update?

I know all of these containers are awesome, but...

Working on bwa container for aphl docker 2023 workshop

**Comment by erinyoung** [comment]
I think this is a great choice! The 'test' layer may be a challenge, but I think it'll be a good learning opportunity!

**Comment by erinyoung** [comment]
Completed with https://github.com/StaPH-B/docker-builds/pull/586
