### ISSUE TITLE
[Docker Workshop]: SeqKit v2.3.1

### ISSUE THREAD

**Issue by hkunerth** [StaPH-B/docker-builds#554]
### What tool are you looking for and why?

I am looking to build a dockerfile for [SeqKit ](https://github.com/shenwei356/seqkit) as a part of the Docker Bioinformatics Workshop.

**Comment by erinyoung** [comment]
This will be a great addition to the docker-builds repo! Good choice!

**Comment by erinyoung** [comment]
Completed with https://github.com/StaPH-B/docker-builds/pull/576
