### ISSUE TITLE
[Docker Workshop]: Kleborate version 2.3.1

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#556]
### What container needs an update?

Should be a simple upgrade given we have a dockerfile for v2.2.0! There doesn't look to be any dependency changes.

Would be a great first contribution (APHL docker workshop trainees 👀)

https://github.com/katholt/Kleborate/releases/tag/v2.3.0

**Comment by bjeong4** [comment]
I chose this task as a start for Docker workshop

**Comment by kapsakcj** [comment]
Newer version was just released, where unit tests are fixed: https://github.com/katholt/Kleborate/releases/tag/v2.3.1

**Comment by kapsakcj** [comment]
I can take care of this one, unless you would like more practice, Byeong 😁 I know you already had a dockerfile in progress

**Comment by erinyoung** [comment]
Are one of you working on this?

**Comment by bjeong4** [comment]
Hi, Erin

I am out of office but will reengage on canu tomorrow when i return.  It is done adding app and test layer. I need to add readme file regarding this container. I am not working on Klaboate now.  Sorry for the late job done.

Byeong

Sent from my Galaxy



-------- Original message --------
From: Young ***@***.***>
Date: 2/15/23 3:47 PM (GMT-05:00)
To: StaPH-B/docker-builds ***@***.***>
Cc: Byeong ***@***.***>, Comment ***@***.***>
Subject: Re: [StaPH-B/docker-builds] [Docker Workshop]: Kleborate version 2.3.1 (Issue #556)


Are one of you working on this?

**Comment by erinyoung** [comment]
@bjeong4 No worries! I'm just cleaning up the issues and setting my tasks for the near future.
