### ISSUE TITLE
[Docker Workshop]: fasttree - Missing app & test layer (Docker workshop)

### ISSUE THREAD

**Issue by danielevansr** [StaPH-B/docker-builds#558]
### What container needs an update?

I know all of these containers are awesome, but...

I'm updating the [FastTree](https://github.com/StaPH-B/docker-builds/blob/master/fasttree/2.1.11/Dockerfile) container with app and test layers for the Intro to Docker 2023 workshop.

**Comment by erinyoung** [comment]
Good choice!

Adding an app and test layer and few minor things will be really helpful. I bet this reduces the image size (current size is 110.4 MB)

**Comment by erinyoung** [comment]
https://github.com/StaPH-B/docker-builds/pull/594 completes this issue

The image is now 27.51 MB
