### ISSUE TITLE
[Docker Workshop]: update ivar 1.3.1 to include new fixes for docker workshop

### ISSUE THREAD

**Issue by jbell-cdph** [StaPH-B/docker-builds#559]
### What container needs an update?

I know all of these containers are awesome, but...

**Comment by erinyoung** [comment]
This is a great dockerfile to update. 

It looks like it mainly needs an app and test stage and a test.

**Comment by erinyoung** [comment]
My apologies, but I created a new image for ivar 1.3.2 (https://github.com/StaPH-B/docker-builds/pull/578). Are you still working on the one for 1.3.1?

**Comment by jbell-cdph** [comment]
Hi Erin—

   Yeah, I got behind because of all the fires to put out here.   Should I continue with ivar, or find a different tool?   I would like to finish the exercises one way or another if possible.

Best
John
