### ISSUE TITLE
[Docker Workshop]: add Freyja 1.3.12

### ISSUE THREAD

**Issue by DOH-KEW4303** [StaPH-B/docker-builds#561]
### What container needs an update?

I know all of these containers are awesome, but...

**Comment by erinyoung** [comment]
Perfect! This will address https://github.com/StaPH-B/docker-builds/issues/560

This dockerfile already has most of everything in place (I think), so will likely only need to change one of the ARGs.

**Comment by kapsakcj** [comment]
FYI - someone has opened a PR to add a dockerfile for freyja 1.3.12

PR #597 

Apologies if you had already started working on this one - there are plenty of other options to choose from

**Comment by DOH-KEW4303** [comment]
OH darn yes I was working on the PR myself last night but had some issues. I am actually out of office so I missed the chance to ask the questions I had in office hours yesterday. I can definitely work on a different one, I just won't be back in the office until next Thursday! Thank you.
