### ISSUE TITLE
[Docker Workshop]: lyve-SET v1.14f

### ISSUE THREAD

**Issue by erikwolfsohn** [StaPH-B/docker-builds#562]
### What container needs an update?

I know all of these containers are awesome, but...

Update docker container && some components of the lyve-SET workflow

**Comment by erinyoung** [comment]
This is a great choice! I think updating this dockerfile is going to be really helpful, and may reduce the size of the image.

**Comment by erinyoung** [comment]
This is connected to PR https://github.com/StaPH-B/docker-builds/pull/582
