### ISSUE TITLE
[Docker Workshop]: add sickle v1.33

### ISSUE THREAD

**Issue by genizamt** [StaPH-B/docker-builds#563]
### What tool are you looking for and why?

adding new tool not yet in repo. Sickle is available on dockerhub https://hub.docker.com/r/ksimons77/sickle

**Comment by erinyoung** [comment]
Are you still working on this or should we close the issue?

**Comment by erinyoung** [comment]
Thank you for your participation in APHL's Docker workshop! I'm going to close this issue, but you are still more than welcome to create Dockerfiles for the StaPH-B/docker-builds repo.
