### ISSUE TITLE
[Docker Workshop]: circlator for workshop

### ISSUE THREAD

**Issue by johnsonj161** [StaPH-B/docker-builds#564]
### What container needs an update?

I know all of these containers are awesome, but...

App and test layer need to be added to [circulator Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/circlator/1.5.6/Dockerfile) to be compatible with GitHub action workflows

**Comment by erinyoung** [comment]
This is a great one!

**Comment by erinyoung** [comment]
Are you still working on this? I ran into a but with StaPH-B's current image https://github.com/StaPH-B/docker-builds/issues/601, but I don't want to step on anyone's toes.

**Comment by johnsonj161** [comment]
Hey @erinyoung, I am not currently working on this. I got too bogged down at work, so feel free to do whatever you need!

**Comment by erinyoung** [comment]
Thank you for letting me know! 

Also, if you come across a tool or version in the future that you'd like to make an image for, don't hesitate to use this resource.
