### ISSUE TITLE
[Docker Workshop]: ncbi/datasets Release v14.7.0

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#565]
### What container needs an update?

ncbi/datasets Release v14.7.0

This fixes a bug that limited results to 1000

**Comment by eproctor118** [comment]
I'd like to work on this one.

**Comment by erinyoung** [comment]
Are you still working on this? If not, I'd like to create the image for the newest release.

**Comment by eproctor118** [comment]
Hello,

Yes, I have the new version's container made. I just need to commit it to
the GitHub repository. With my workload the way it is right now, I'll be
able to get to it next week. If you need it sooner than that, please move
forward with the update.

Thank you!
Elizabeth

**Comment by erinyoung** [comment]
I can wait until next week. I hope your workload becomes more manageable!
