### ISSUE TITLE
[Request An Update]: TBProfiler Release v4.4.1 

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#566]
### What container needs an update?

There's a new version of TBProfiler

**Comment by kapsakcj** [comment]
if no one from the workshop chooses this, I can take care of it

**Comment by erinyoung** [comment]
I don't think anyone is working on this

**Comment by kapsakcj** [comment]
OK, I'll submit a PR in the near future

**Comment by erinyoung** [comment]
Thanks!

Closed with https://github.com/StaPH-B/docker-builds/pull/608
