### ISSUE TITLE
[Docker Workshop]: masurca v4.1.0

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#567]
### What container needs an update?

There's a new version of masurca available

**Comment by gabrielanine** [comment]
Hello, I would like to select this tool for the project please. Thank you, Gabriela Nine

**Comment by erinyoung** [comment]
Perfect!

**Comment by erinyoung** [comment]
Are you still working on this? I would like to use the newest version of Masurca, but I don't want to step on any toes.
