### ISSUE TITLE
[Docker Workshop]: bowtie2 version 2.4.4

### ISSUE THREAD

**Issue by Siddra2021** [StaPH-B/docker-builds#569]
### What container needs an update?

I know all of these containers are awesome, but... will work on bowtie2 v 2.4.4

**Comment by erinyoung** [comment]
I think this is an okay Dockerfile to work on. In your pull request, please remind me to not overwrite the 'latest' tag when we deploy to dockerhub and quay.

**Comment by erinyoung** [comment]
Are you still working on this or should we close this issue?

**Comment by Siddra2021** [comment]
I am done with this on my part.

Siddra
