### ISSUE TITLE
[Docker Workshop]:  cfsan-snp (v2.0.2) container missing app and test layer

### ISSUE THREAD

**Issue by sam-baird** [StaPH-B/docker-builds#570]
### What container needs an update?

I know all of these containers are awesome, but...

I would like to work on adding an app and test layer to the [cfsan-snp Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/cfsan-snp-pipeline/2.0.2/Dockerfile) for the APHL 2023 Docker workshop.

**Comment by erinyoung** [comment]
Associated with https://github.com/StaPH-B/docker-builds/pull/606

**Comment by erinyoung** [comment]
Thank you for your contribution!
