### ISSUE TITLE
[Docker Workshop]: augur v20.0.0

### ISSUE THREAD

**Issue by smarcellus16** [StaPH-B/docker-builds#572]
### What container needs an update?

I know all of these containers are awesome, but...

**Comment by erinyoung** [comment]
Version 6? Not version 20.0.0?

**Comment by erinyoung** [comment]
Actually, I think I confused 'augr' with 'augur'. My apologies!

**Comment by erinyoung** [comment]
Perfect! This is a great one to work on! Augur may have had some updates and some dependency changes.

**Comment by erinyoung** [comment]
Are you still working on this or should we close the issue?
