### ISSUE TITLE
[Bug]: phyml error

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#589]
### What container were you trying to use, and how were you attempting to use it?

CC @jvhagey - have you encountered this error before?

When using `staphb/phyml:3.3.20220408` docker image, I got an error `Illegal instruction (core dumped)`

The error seems related to CPU instructions and the phyml GH Issues is littered with reports of this error: https://github.com/stephaneguindon/phyml/issues?q=is%3Aissue+core+dump

perhaps the dockerfile/image is missing `openmpi`? [The bioconda recipe includes it](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/phyml/meta.yaml). We could try adding `apt-get install openmpi-bin` to see if that resolves the issue

To reproduce (input file attached):
```bash
# start container in interactive mode
$ docker run --rm=True -u $(id -u):$(id -g) -v $(pwd):/data -ti staphb/phyml:3.3.20220408

$ phyml -i snvAlignment.phy --datatype nt --model GTR -v 0.0 -s BEST --ts/tv e --nclasses 4 --alpha e --bootstrap -4 --quiet
Illegal instruction (core dumped)
```
When I install via bioconda (albeit an earlier version of phyml), I do not receive this error. It runs as expected:

```bash
$ mamba create -n phyml -c conda-forge -c bioconda -c defaults phyml

$ phyml --version

. This is PhyML version 3.3.20211231.

$ phyml -i snvAlignment.phy --datatype nt --model GTR -v 0.0 -s BEST --ts/tv e --nclasses 4 --alpha e --bootstrap -4 --quiet

. The BEST option is deprecated. PhyML now uses a mix of SPRs and NNIs.





  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:                             snvAlignment.phy
        . Data type:                                     dna
        . Alphabet size:                                 4
        . Sequence format:                               interleaved
        . Number of data sets:                           1
        . Nb of bootstrapped data sets:                  0
        . Compute approximate likelihood ratio test:     yes (SH-like branch supports)
        . Model name:                                    GTR
        . Proportion of invariable sites:                0.000000
        . RAS model:                                     discrete Gamma
        . Number of subst. rate catgs:                   4
        . Gamma distribution parameter:                  estimated
        . 'Middle' of each rate class:                   mean
        . Nucleotide equilibrium frequencies:            empirical
        . Optimise tree topology:                        yes
        . Starting tree:                                 BioNJ
        . Add random input tree:                         no
        . Optimise branch lengths:                       yes
        . Minimum length of an edge:                     1e-08
        . Optimise substitution model parameters:        yes
        . Run ID:                                        none
        . Random seed:                                   1675895550
        . Subtree patterns aliasing:                     no
        . Version:                                       3.3.20211231
        . Byte alignment:                                16
        . AVX enabled:                                   no
        . SSE enabled:                                   yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////




. Log likelihood of the current tree: -373.930670424939421536692.

. Time used 0h0m0s

oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

**Comment by kapsakcj** [comment]
test input file:

[snvAlignment.phy.txt](https://github.com/StaPH-B/docker-builds/files/10690507/snvAlignment.phy.txt)

Remove the `.txt` off the end

**Comment by jvhagey** [comment]
Yes, unfortunately its been on my to do list for quite some time... https://github.com/DHQP/SNVPhyl_Nextflow/issues/1 . Alyssa  looked into it, but I never got to getting it a fix. 😬

**Comment by kapsakcj** [comment]
Understood. Some additional info that may help troubleshoot the issue - in addition to the bioconda package running successfully, the biocontainer for the corresponding bioconda package resolved the issue for P.

I believe he used the docker image `quay.io/biocontainers/phyml:3.3.20211231--hee9e358_0` from here: https://quay.io/repository/biocontainers/phyml?tab=tags

**Comment by jvhagey** [comment]
ok nice, I will try it today and see if it works. Thanks for following up on this!

**Comment by jvhagey** [comment]
@kapsakcj, so oddly enough on one of our clusters the old container works, but that doesn't work on the other cluster. The new container works on both so I say lets go with the new one. Do you want to push the changes? Thanks for getting it sorted!!

**Comment by kapsakcj** [comment]
great, thanks for testing! I'll ping back when the docker image tag has been overwritten on dockerhub & quay

**Comment by kapsakcj** [comment]
OK, docker image has been rebuilt locally on my VM and pushed to [dockerhub](https://hub.docker.com/r/staphb/phyml/tags) and [quay](https://quay.io/repository/staphb/phyml?tab=tags) for 4 tags:

`quay.io/staphb/phyml:3.3.20220408`
`quay.io/staphb/phyml:latest`
`staphb/phyml:3.3.20220408`
`staphb/phyml:latest`

please let us know if you run into issues again and we can troubleshoot further
