### ISSUE TITLE
[Request For Comment]: Add `pigz` to the SPAdes container

### ISSUE THREAD

**Issue by fanninpm** [StaPH-B/docker-builds#592]
### What container needs an update?

I know all of these containers are awesome, but SPAdes can use `pigz` to compress mutliple files at once. (I think it should be as simple as adding `pigz` to the `apt-get` command.)

**Comment by kapsakcj** [comment]
Feel free to open a PR for the Dockerfile for the latest version of SPAdes, or whichever version you are using, and we can add it

If not, I can get this added once I have some free time

**Comment by kapsakcj** [comment]
@fanninpm I made a draft PR for this change & pushed the docker image to dockerhub for testing `kapsakcj/spades:3.15.5` https://hub.docker.com/r/kapsakcj/spades/tags

Let me know if you have any feedback before we merge the PR and redeploy the spades 3.15.5 docker image

Today I Learned that spades can use `pigz`! Thanks!

**Comment by kapsakcj** [comment]
Closed via PR #605 

the updated docker image will be on dockerhub and quay shortly
