### ISSUE TITLE
[Request An Update]: VADR v1.5.1

### ISSUE THREAD

**Issue by fanninpm** [StaPH-B/docker-builds#602]
### What container needs an update?

I know all of these containers are awesome, but VADR recently released version 1.5.1, which includes a couple of bug fixes that cropped up in RSV annotation.

(This would also be a good excuse to slim down the image, as `docker images` currently shows its `SIZE` as `6.03 GB`.)

**Comment by kapsakcj** [comment]
It's on my todo list! Thanks for submitting the issue
