### ISSUE TITLE
[Request An Update]: samtools 1.17

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#610]
### What container needs an update?

[There's a new version of samtools available](https://twitter.com/htslib/status/1628040492104515584)

**Comment by HarryHung** [comment]
Starting with [SAMtools](https://github.com/StaPH-B/docker-builds/tree/master/samtools) and [BCFtools](https://github.com/StaPH-B/docker-builds/tree/master/bcftools)?

**Comment by erinyoung** [comment]
htslib, samtools, and bcftools are all tied to the same version, so they could all use an update.
