### ISSUE TITLE
[Container Request]: MIDAS

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#668]
### What tool are you looking for and why?

Sam Minot (Fred Hutch) provides a docker image for MIDAS, but it would be good to have our own dockerfile & image here, as it will be relevant to PulseNet 2.0

https://github.com/snayfach/MIDAS

https://github.com/FredHutch/docker-midas provides a starting point for the Dockerfile

https://quay.io/repository/fhcrc-microbiome/midas?tab=tags

**Comment by Kincekara** [comment]
I tried creating a docker image for MIDAS, and I ended up with ~650 MB. Sam Minot's image has a similar size too. Biocontainers has a 195MB image for this.
https://quay.io/repository/biocontainers/midas?tab=tags 

I haven't tried it, but a micromamba base image with the bioconda recipe may be a better option for creating this image.

**Comment by Kincekara** [comment]
Please ignore my previous comment. I realized that I compared uncompressed size. I can build a small-size image successfully. I will create a pull request after testing it externally too.

**Comment by erinyoung** [comment]
Addressed via https://github.com/StaPH-B/docker-builds/pull/691, so I'm closing this issue

Thank you for your contribution!!!
