### ISSUE TITLE
jellyfish not found

### ISSUE THREAD

**Issue by Hubbins29** [StaPH-B/docker-builds#67]
Using Singularity and kraken 1.1.1. While attempting to run kraken-build the following error is thrown
"/opt/kraken/check_for_jellyfish.sh: line 27: jellyfish: command not found"

**Comment by kapsakcj** [comment]
Hey Matt, thanks for the issue. It's an issue with the PATH. Can you run the container in interactive mode  via `singularity shell ...` and run this: `PATH="$PATH:/opt/bin"` before re-trying `kraken-build`? If that works for you, I can adjust the PATH variable set in the dockerfile.

**Comment by Hubbins29** [comment]
That looks to have fixed the issue. Thanks.

**Comment by kapsakcj** [comment]
Cool! Thanks for the issue. I'll update the docker images and push new versions to dockerhub

**Comment by kapsakcj** [comment]
Images for both kraken 1.0 and 1.1.1 are building on dockerhub now. Should be ready in an hour or so.
