### ISSUE TITLE
tbl2asn expires in all prokka images

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#68]
affects the following dockerhub tags: `1.13` , `1.14.0`, `1.14.0-cv2`, `1.14.5`, and `latest` (yes, all of them...)

```
[14:38:46] Looking for 'tbl2asn' - found /prokka-1.14.0/bin/../binaries/linux/tbl2asn
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[14:38:46] Determined tbl2asn version is 25.7
```

Can't wait for Torsten to remove `tbl2asn` as a dependency 

https://github.com/tseemann/prokka/issues/453

**Comment by kapsakcj** [comment]
https://github.com/StaPH-B/docker-builds/commit/dfecffab2614f6400bc72b19adcc2a2f2c4151a7

Hopefully fixed ^^. Local testing checks out for all prokka versions. Waiting to rebuild on dockerhub.

**Comment by kapsakcj** [comment]
All images are rebuilt on dockerhub now and `tbl2asn` functions properly. Yay!

**Comment by lucaspompeun** [comment]
What I have to do to fix this problem?

**Comment by kapsakcj** [comment]
re-download the image from dockerhub and you should be good. Please let me know if you have an issue running it.

**Comment by lucaspompeun** [comment]
Can I just use `docker build --tag tbl2asn` ?

**Comment by kapsakcj** [comment]
Sure, if you want to build the image from scratch. You'll need to provide a path to where the dockerfile is located `docker build --tag tbl2asn prokka/1.14.5/`
