### ISSUE TITLE
[Container Request]: add shigatyper 2.0.4

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#682]
### What tool are you looking for and why?

Includes a fix for Shigella flexneri serotype prediction. See details here: https://github.com/CFSAN-Biostatistics/shigatyper/issues/11

Can use the pre-existing dockerfile for v2.0.3 as a starting point

Could improve the docker image by adding a `builder` stage and handling the `samtools` compilation step within this stage. Similar to how this dockerfile is written: https://github.com/StaPH-B/docker-builds/blob/master/samtools/1.17-2023-06/Dockerfile

It would make the final docker image much smaller since we can remove all the stuff required for compiling the samtools C code

**Comment by jwarnn** [comment]
Wow, this ```builder``` strategy sounds really useful for optimization. For more documentation on this from Docker, you may find this link helpful: https://docs.docker.com/build/building/multi-stage/. Thanks to @kapsakcj for sharing this valuable resource! I will work on updating this tool.

**Comment by kapsakcj** [comment]
just pushed a commit to get the docker image building successfully. Adding the `builder` stage really helps bring down the final image size:

```
$ docker images | grep '2.0.4-'
kapsakcj/shigatyper     2.0.4-test      64773b78b89e   8 minutes ago    842MB
kapsakcj/shigatyper     2.0.4-app       68185d81276c   21 minutes ago   308MB
kapsakcj/shigatyper     2.0.4-builder   01762b5ae7ff   31 minutes ago   884MB
```

**Comment by kapsakcj** [comment]
@jwarnn Please let me know if you have any feedback on the dockerfiles I've added in PR #688 (they are nearly identical, except for the version of shigatyper and a few download links)
