### ISSUE TITLE
[Request An Update]: Freyja

### ISSUE THREAD

**Issue by jl32587** [StaPH-B/docker-builds#684]
### What container needs an update?

There was a new version of Freyja coming out 2 weeks ago, https://github.com/andersen-lab/Freyja/releases/tag/v1.4.4

Would appreciate if someone could help update to the latest version.

**Comment by erinyoung** [comment]
There's a PR for this tool and version. You can keep track of progress here : https://github.com/StaPH-B/docker-builds/pull/678
