### ISSUE TITLE
[Request An Update]: samtools v1.18

### ISSUE THREAD

**Issue by fanninpm** [StaPH-B/docker-builds#695]
### What container needs an update?

I know all of these containers are awesome, but... [samtools recently got updated to v1.18](https://github.com/samtools/samtools/releases/tag/1.18).

**Comment by kapsakcj** [comment]
PRs are welcome 😉 ! But I can submit a PR soon for updates to samtools, bcftools, htslib later this week if no one beats me to it.

Both the bcftools and htslib dockerfiles need re-working to incorporate a `builder` stage as we have for `samtools` as it dramatically reduces the final docker image size

**Comment by erinyoung** [comment]
I'm on it! https://github.com/StaPH-B/docker-builds/pull/699

**Comment by kapsakcj** [comment]
PR closed & opened another PR #707

**Comment by kapsakcj** [comment]
closed via PR #707 

Docker images for htslib, bcftools, and samtools 1.18 should be available on dockerhub and quay.io shortly 🎉
