### ISSUE TITLE
[Container Request]: BUSCO v5.4.7

### ISSUE THREAD

**Issue by Kincekara** [StaPH-B/docker-builds#700]
### What tool are you looking for and why?

BUSCO is a tool that evaluates assemblies by using datasets of near-universal single-copy orthologs derived from OrthoDB.
Ezlab has its own BUSCO docker, but it would be good to have it here too.

https://busco.ezlab.org/
https://gitlab.com/ezlab/busco/-/releases#5.4.7

If it is desired, I can make a PR for this.

**Comment by kapsakcj** [comment]
Would appreciate it if you do end up making a dockerfile & image 👍 

We run this tool routinely and rely on Ezlab's docker image

I'm happy to help where possible

**Comment by erinyoung** [comment]
Addressed by https://github.com/StaPH-B/docker-builds/pull/701
