### ISSUE TITLE
[Request An Update]: AMRFinderPlus 3.11.18

### ISSUE THREAD

**Issue by Kincekara** [StaPH-B/docker-builds#705]
### What container needs an update?

I know all of these containers are awesome, but AMRFinderPlus has a new release.

https://github.com/ncbi/amr/releases

**Comment by kapsakcj** [comment]
I can work on this, especially given that a new database was just released `2022-08-08.2`

**Comment by kapsakcj** [comment]
opened a PR to address this issue, see #706
