### ISSUE TITLE
[Request An Update]: There is a new version of Freyja v1.4.5

### ISSUE THREAD

**Issue by jessres** [StaPH-B/docker-builds#708]
### What container needs an update?

(https://github.com/andersen-lab/Freyja/releases/tag/v1.4.5)

**Comment by kapsakcj** [comment]
thanks for the heads up, we can get this added soon. I'll start a dev branch and open a PR

**Comment by kapsakcj** [comment]
closed via PR #709 . The docker image is now available on dockerhub and quay

https://hub.docker.com/r/staphb/freyja

https://quay.io/repository/staphb/freyja?tab=tags
