### ISSUE TITLE
[Container Request]: bandage

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#712]
### What tool are you looking for and why?

The biocontainers image works great, but we don't currently have this one on StaPH-B

**Comment by logan-fink** [comment]
I can take this one for the Docker Workshop if no one has taken it yet.

**Comment by erinyoung** [comment]
No one has taken this, yet!

The prior version of Bandage is missing an 'app' and 'test' stage, but Dr. Wick is really good at providing test files (https://github.com/rrwick/Bandage/blob/main/tests/test_plasmids.gfa)

**Comment by erinyoung** [comment]
@logan-fink , are you still working on this?

**Comment by erinyoung** [comment]
@logan-fink , I'm just checking in. Are you still working on a bandage image?
