### ISSUE TITLE
[Request An Update]: new version of dnaapler

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#715]
### What container needs an update?

dnaapler has a new version (https://github.com/gbouras13/dnaapler/releases).

Version 2.0 has some additional features that may be useful.

**Comment by evagunawan** [comment]
I can cover this one for the docker workshop as well as make a Dockerfile from scratch for a program I am working on.

**Comment by erinyoung** [comment]
Thank you @evagunawan for working on this! I'm closing this issue since you've resolved this.
