### ISSUE TITLE
[Request An Update]: ncbi datasets

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#719]
### What container needs an update?

There's a new version of datasets : https://github.com/ncbi/datasets/releases

This one is really easy to update.

**Comment by alxespinosa** [comment]
I want to work on this one.

**Comment by erinyoung** [comment]
Perfect! This is one that I recommend to users wanting to get their feet wet in building docker images.

**Comment by erinyoung** [comment]
@alxespinosa , are you still working on this?

**Comment by alxespinosa** [comment]
Hi Erin,

I am no longer working on this.  Thanks for checking though.

Best,
Alex

CONFIDENTIALITY NOTICE WARNING: This transmission may contain confidential and proprietary information intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you have received this transmission in error, any disclosure, copying, distribution, downloading, uploading or the taking of any action in reliance on the contents of this information is strictly prohibited, and you are requested to immediately notify the above sender.
