### ISSUE TITLE
[Request An Update]: Freyja version 1.4.6

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#722]
### What container needs an update?

There's a new version of Freyja!

https://github.com/andersen-lab/Freyja/releases/tag/v1.4.6

Most notably, now pulls barcodes from GISAID tree by default

**Comment by erinyoung** [comment]
Addressed in https://github.com/StaPH-B/docker-builds/pull/752

**Comment by laura-bankers** [comment]
@erinyoung - I can work on addressing this issue as part of the docker training workshop.

**Comment by erinyoung** [comment]
Perfect! It's a tool that a lot of people use, so the prior Dockerfile versions should be a good springboard for updating this.

**Comment by erinyoung** [comment]
@laura-bankers , I'm just checking in. Are you still working on this?

**Comment by laura-bankers** [comment]
@erinyoung - yep! working on it this week (1.4.7 was recently released so going to do that)

**Comment by laura-bankers** [comment]
@erinyoung - PR sent: https://github.com/StaPH-B/docker-builds/pull/792

**Comment by erinyoung** [comment]
Thank you for working on this!
