### ISSUE TITLE
[Request An Update]: BLAST+ 2.14.1

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#724]
### What container needs an update?

There's a new version of blast!

> https://blast.ncbi.nlm.nih.gov/doc/blast-news/2023-BLAST-News.html
> BLAST+ 2.14.1 Now Available
> BLAST+ 2.14.1 is now available with improved documentation, faster and more reliable database downloads, and some bug fixes.

**Comment by Haikelnb** [comment]
Would like to work on this for the workshop

**Comment by erinyoung** [comment]
Perfect!

The Dockerfile from a prior version should be a good starting point for you.
