### ISSUE TITLE
[Request An Update]: Fastani version 1.34

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#730]
### What container needs an update?

fastANI has a new version!

https://github.com/ParBLiSS/FastANI/releases/tag/v1.34
> Compared to v1.33, this version fix multi-threading output bugs, adds test scripts, adds build with cmake and removes the build with autoconf . Output and interface of FastANI remains same as before.

Looks like there's some new tests that we could incorporate into the new Dockerfile.

**Comment by Kincekara** [comment]
Almost ready! But, I am not sure how we can incorporate the new tests.

**Comment by erinyoung** [comment]
Addressed in https://github.com/StaPH-B/docker-builds/pull/752
