### ISSUE TITLE
[Request An Update]: Freebayes version 1.3.7

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#731]
### What container needs an update?

Freebayes has a new version!

https://github.com/freebayes/freebayes/releases/tag/v1.3.7

Personally, I'm most excited about 
> tweaks to improve performance on long reads

**Comment by kittychaseNC** [comment]
I will update this
-Kitty

**Comment by erinyoung** [comment]
Perfect!

Hopefully the new version builds as smoothly as I think it will.

**Comment by erinyoung** [comment]
Closed by https://github.com/StaPH-B/docker-builds/pull/775
