### ISSUE TITLE
[Request An Update]: minimap2 to version 2.26

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#736]
### What container needs an update?

Minimap2 has a new version!

https://github.com/lh3/minimap2/releases/tag/v2.26

Notes from the creator.
> Fixed the broken Python package. This is the only change.

This seems to mainly impact Illumina long-read

**Comment by arianna-smith** [comment]
I can work on this for the Docker workshop. Arianna Smith - CDPHE

**Comment by erinyoung** [comment]
Perfect!

**Comment by erinyoung** [comment]
@arianna-smith , are you still working on this?

**Comment by arianna-smith** [comment]
@erinyoung yes! I will have it uploaded either today or tomorrow!

**Comment by erinyoung** [comment]
@arianna-smith , I'm just checking in. Did you run into any issues?

**Comment by arianna-smith** [comment]
@erinyoung I just created the pull request!

**Comment by erinyoung** [comment]
Thank you for your contribution!
