### ISSUE TITLE
[Request An Update]: skesa

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/docker-builds#748]
### What container needs an update?

There's a newer version of skesa! Well, not really. It looks like skesa itself is still being called version 2.4.0, but saute is now version 1.3.0_2 and is included with it.

The prior [Dockerfile](https://github.com/StaPH-B/docker-builds/blob/master/skesa/2.4.0/Dockerfile) is missing the app and test stages, as well as a CMD line, so there's going be some working getting this latest image together.

**Comment by krithisankar2** [comment]
I can work on this for the Docker workshop.

**Comment by erinyoung** [comment]
Perfect!

The prior Dockerfile is going to need a lot of work to bring it up to current standards, but I think you're going to learn a lot!

**Comment by erinyoung** [comment]
@krithisankar2 , are you still working on this?

**Comment by krithisankar2** [comment]
> @krithisankar2 , are you still working on this?
Yes. I was caught up with some pipeline development at work. I should be finishing my tests and sending a PR by end of this week.

**Comment by erinyoung** [comment]
@krithisankar2 , I'm just checking in. Did you run into any additional problems?
