### ISSUE TITLE
[Request An Update]: nanoplot

### ISSUE THREAD

**Issue by MrTomRod** [StaPH-B/docker-builds#751]
### What container needs an update?

There is a new version out:  v1.41.6

https://github.com/wdecoster/NanoPlot/releases

Thanks for your great work!

**Comment by kprus** [comment]
I will work on this as part of the APHL Docker workshop.

**Comment by erinyoung** [comment]
Perfect!

I will close https://github.com/StaPH-B/docker-builds/issues/720 and focus on this thread.
