### ISSUE TITLE
[Request An Update]: The bcftools container missing the plugins

### ISSUE THREAD

**Issue by adhroso** [StaPH-B/docker-builds#755]
### What container needs an update?

I know all of these containers are awesome, but...can we include the plugins directory (when installed: /usr/local/libexec/bcftools) or when it is build, the libs are under ./bcftools-1.18/plugins.

Thank you sooo much!!!

**Comment by kapsakcj** [comment]
Thanks for filing the issue. Could you elaborate a little bit more on this request? I have not used these plugins before and want to make sure we implement changes correctly. Is it as simple as adding a new environmental variable to the dockerfile?

```Dockerfile
ENV BCFTOOLS_PLUGINS=/path/to/bcftools/plugins
```

https://github.com/samtools/bcftools/blob/2c81697ca69fa6db8ca12b9ab67fd3739cd5c9ed/INSTALL#L19

We also welcome pull requests if you're able to submit one. If not, one of the maintainers should be able to update the dockerfile in the next couple of weeks

**Comment by erinyoung** [comment]
@adhroso , we would like to address this issue. 

Is there a plugin that you use that we could use for testing?

**Comment by erinyoung** [comment]
@adhroso , I've been reading https://samtools.github.io/bcftools/howtos/plugins.html since I put together the Dockerfile bcftools version 1.19.

I think all we need to do is add a directory and set environmental variable to it.

**Comment by erinyoung** [comment]
I learned via a conversation in slack that the plugins are actually part of the source code for bcftools. It looks like it just needed to be copied over.

**Comment by erinyoung** [comment]
@adhroso , I think we've resolved your issue with version 1.19 (https://hub.docker.com/r/staphb/bcftools/tags). Let us know if you run into issues!
