### ISSUE TITLE
condense ENV layers into one for all dockerfiles

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#78]
This: 
```Dockerfile
# set PATH and perl local settings
ENV PATH="${PATH}:/mlst-2.19.0/bin:\
/ncbi-blast-2.9.0+/bin" \
    LC_ALL=C
```
uses one layer to set env variables, where as the below examples adds an unnecessary layer to the docker image:
```Dockerfile
ENV PATH="${PATH}:/mlst-2.17.6/bin:\
/ncbi-blast-2.9.0+/bin"

# set perl locale settings
ENV LC_ALL=C
```

This could be applied across all of our Dockerfiles that has more than one `ENV` layer

**Comment by erinyoung** [comment]
I think most people are following this guidance. Can we close this issue?
