### ISSUE TITLE
[Container Request]: el_gato

### ISSUE THREAD

**Issue by Kincekara** [StaPH-B/docker-builds#781]
### What tool are you looking for and why?

El_gato is a bioinformatics tool that utilizes either a genome assembly (.fasta) or Illumina paired-end reads (.fastq) to replicate Legionella pneumophila Sequence Based Typing (SBT)

GitHub: https://github.com/appliedbinf/el_gato

**Comment by kapsakcj** [comment]
FYI I believe they are in the process of submitting to bioconda, so eventually a biocontainer will be built. But regardless it would be nice to have in here to in case the biocontainer is insufficient/not compatible with workflow managers/or some other reason
