### ISSUE TITLE
[Bug]: Container not on docker/quay

### ISSUE THREAD

**Issue by arianna-smith** [StaPH-B/docker-builds#797]
### What container were you trying to use, and how were you attempting to use it?

The new staphb/artic container does not exist on dockerhub or quay.

**Comment by erinyoung** [comment]
That's embarrassing!

Looks like the PR got merged, but then the image was never deployed. Thank you for brining this to our attention.

I'm deploying this now. You can check the status of the deploy here : https://github.com/StaPH-B/docker-builds/actions/runs/6880502294

**Comment by erinyoung** [comment]
It looks like it is there now. https://hub.docker.com/r/staphb/artic/tags

Thank you for letting us know!
