### ISSUE TITLE
add legsta 0.5.1

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#80]
@garfinjm just FYI Torsten released this yesterday. Not sure if you're interested in upgrading versions or not.

New dependency - `any2fasta`. This one is really easy to install:
```Dockerfile
# get any2fasta
RUN cd /usr/local/bin && \
  wget https://raw.githubusercontent.com/tseemann/any2fasta/master/any2fasta && \
  chmod +x any2fasta

# no need to update PATH since it's in /usr/local/bin
```

https://github.com/tseemann/legsta/releases/tag/v0.5.1

**Comment by garfinjm** [comment]
I should be able to get this updated and tested sometime this week. Looks pretty straightforward.

**Comment by kapsakcj** [comment]
No rush at all...I think you might be the only person that uses it :)

**Comment by kapsakcj** [comment]
Done in: https://github.com/StaPH-B/docker-builds/commit/b5faa29cc5f27093a9e14097eb6b78dff604eead

I will test w/ singularity, but don't expect any issues there
