### ISSUE TITLE
add Flye 2.7

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#81]
https://github.com/fenderglass/Flye/releases/tag/2.7

**Comment by AbigailShockey** [comment]
I can also take this one

**Comment by kapsakcj** [comment]
TY, would love to test once it's ready!

**Comment by kapsakcj** [comment]
Done in https://github.com/StaPH-B/docker-builds/commit/08824c6720b6633015ff54e82830a2e044903c20

Thank you @AbigailShockey !!
