### ISSUE TITLE
[Request An Update]: ncbi-amrfinderplus to v3.11.26

### ISSUE THREAD

**Issue by Kincekara** [StaPH-B/docker-builds#810]
### What container needs an update?

Amrfinder has a new relase: https://github.com/ncbi/amr/releases/tag/amrfinder_v3.11.26

Also, a new database : [2023-11-15.1](https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.11/2023-11-15.1/changes.txt)

**Comment by kapsakcj** [comment]
We already upgraded to these versions here: https://github.com/StaPH-B/docker-builds/pull/800

Is there something wrong with this docker image?

**Comment by Kincekara** [comment]
Please ignore this. I need more coffee.
