### ISSUE TITLE
[Request An Update]: BUSCO

### ISSUE THREAD

**Issue by Kincekara** [StaPH-B/docker-builds#845]
### What container needs an update?

BUSCO has a new version [5.6.0](https://gitlab.com/ezlab/busco)

**Comment by erinyoung** [comment]
This is awesome!

Can I make a request, though? Can we include the basic bacteria lineage? It's only ~27M when unpacked. 

The path for the most recent one is here : https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb10.2024-01-08.tar.gz

**Comment by Kincekara** [comment]
Sure! I already use a slim version of BUSCO with bacteria_odb (kincekara/busco:5.4.7-bacteria_odb10.2020-03-06)
How about creating a full version, and a slim version with bacteria lineage for prokaryotes?

**Comment by erinyoung** [comment]
Sounds good!
