### ISSUE TITLE
add Canu 2.0

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#85]
Any takers? @k-florek ?

https://github.com/marbl/canu/releases/tag/v2.0

Just wanted to make you aware in case you're interested in trying out the new version.

**Comment by AbigailShockey** [comment]
I did the last update, so I'm on it :)

**Comment by kapsakcj** [comment]
Thanks for taking this one too!

**Comment by kapsakcj** [comment]
Done in https://github.com/StaPH-B/docker-builds/commit/08824c6720b6633015ff54e82830a2e044903c20

Thanks @AbigailShockey
