### ISSUE TITLE
Dockerhub link in readme goes to dockerhub page for artic-ncov2019 instead of artic

### ISSUE THREAD

**Issue by garfinjm** [StaPH-B/docker-builds#852]
Just need to delete `-ncov2019` in the first column of line 111.

https://github.com/StaPH-B/docker-builds/blob/9579e05ab11806f632b7649922feb4db46a213b2/README.md?plain=1#L111

**Comment by erinyoung** [comment]
I've created a PR with the change here : https://github.com/StaPH-B/docker-builds/pull/853

This should be resolved _soon_

**Comment by Kincekara** [comment]
This issue was resolved. Thank you for your contribution!
