### ISSUE TITLE
[Request An Update]: phytreeviz-0.2.0

### ISSUE THREAD

**Issue by DrB-S** [StaPH-B/docker-builds#863]
### What container needs an update?

A new version of phytreeviz (v0.2.0) was released last week. Please update.

**Comment by Kincekara** [comment]
Thank you for the heads up! Phytreeviz v0.2.0 image will be available soon.

**Comment by erinyoung** [comment]
You can check the status of the deployment here : https://github.com/StaPH-B/docker-builds/actions/runs/7802628617
