### ISSUE TITLE
add staramr 0.7.1

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#88]
https://github.com/phac-nml/staramr/releases/tag/0.7.1

There's been a few releases since @stjacqrm made the first dockerfile for staramr.

Just putting this on the radar in case anyone wanted to upgrade versions.

hopefully the only change needed in the dockerfile is `pip3 install staramr==0.7.1` 🤞

**Comment by AbigailShockey** [comment]
Can do

**Comment by kapsakcj** [comment]
Not sure if you had success with this or not @AbigailShockey . I tried this morning, and pip does not want to install 0.7.1, despite me specifying that version. It installs 0.7.0 instead.

I opened an issue here with my in-progress dockerfile https://github.com/phac-nml/staramr/issues/119

**Comment by kapsakcj** [comment]
nvm, Abigail. It was an issue with the package they uploaded to pypi. Will add the dockerfile shortly.

**Comment by AbigailShockey** [comment]
This definitely got lost at the bottom of my to-do list. Thank you for adding the dockerfile!

**Comment by kapsakcj** [comment]
No worries.

Just for future reference:
There was both an issue with the pypi package that the staramr maintainers uploaded to pypi (they promptly fixed 👍 ) and additionally when you run `pip3 install staramr==0.7.1`, that installs `pandas 1.0.3` where as staramr needs `pandas 0.25.3` to run properly. At least for now...

dockerfile added in https://github.com/StaPH-B/docker-builds/commit/c9bd871a4a801c0dc8c82813d25f70fc561154e3
