### ISSUE TITLE
[Container Request]: clair3

### ISSUE THREAD

**Issue by kapsakcj** [StaPH-B/docker-builds#933]
### What tool are you looking for and why?

https://github.com/HKU-BAL/Clair3

variant caller for nanopore data. They provide a dockerfile and pre-built images on dockerhub but may be useful to add our own dockerfile here.

dockerfile for reference: https://github.com/HKU-BAL/Clair3/blob/main/Dockerfile

Looks like a pretty complicated install with various python C/C++ dependencies as well as bioinfo tools like `samtools`. I would probably go with the `micromamba` route and install things via micromamba/conda

**Comment by Kincekara** [comment]
I've created an image for this. I will make a PR after adding a test.
